// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HorizontalAlign } from "./HorizontalAlign.js";
import type { ReadingOrder } from "./ReadingOrder.js";
import type { VerticalAlign } from "./VerticalAlign.js";

/**
 * Cell alignment.
 *
 * schema-excluded: relativeIndent, mergeCell
 */
export type AlignmentPatch = { horizontal?: HorizontalAlign, vertical?: VerticalAlign, wrap?: boolean, indent?: number, textRotation?: number, shrinkToFit?: boolean, justifyLastLine?: boolean, readingOrder?: ReadingOrder, };
