// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";

/**
 * Anchor input: either a two-cell A1 range string (`"A1:E15"`, optionally
 * sheet-qualified) or an explicit {@link ChartAnchor}. The range form is
 * resolved to a `ChartAnchor` in the Rust facade.
 */
export type AnchorSpec = string | ChartAnchor;
