// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiCellValue = { "type": "blank" } | { "type": "string", "value": string } | { "type": "number", "value": number } | { "type": "boolean", "value": boolean } | { "type": "error", "value": string };
