// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorCode =
  | "invalid_ref"
  | "missing_sheet"
  | "duplicate_sheet"
  | "invalid_sheet_name"
  | "cannot_delete_last_sheet"
  | "ooxml_write_error"
  | "other";
