// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorCode } from "./ApiErrorCode.js";

export type ApiError = { code: ApiErrorCode, message: string, sheet?: string, reference?: string, part?: string, };
