// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorCode =
  | "invalid_ref"
  | "missing_sheet"
  | "duplicate_sheet"
  | "invalid_sheet_name"
  | "cannot_delete_last_sheet"
  | "shape_mismatch"
  | "unsupported_style"
  | "merge_overlap"
  | "invalid_hyperlink"
  | "invalid_search_query"
  | "invalid_defined_name"
  | "ooxml_write_error"
  | "other";
