// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoFilterOperator } from "./AutoFilterOperator.js";

export type AutoFilterCustomCriterion = { operator: AutoFilterOperator; value: string };
