// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoFilterColumnInfo } from "./AutoFilterColumnInfo.js";

export type AutoFilterInfo = {
  sheet: string;
  reference: string;
  startRow: number;
  startColumn: number;
  endRow: number;
  endColumn: number;
  columns: Array<AutoFilterColumnInfo>;
};
