// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoFilterCriteria } from "./AutoFilterCriteria.js";

export type AutoFilterColumnPatch = { columnOffset: number, hiddenButton?: boolean, showButton?: boolean, criteria: AutoFilterCriteria, };
