// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 3D bar/column shape (`c:shape/@val`, OOXML `ST_Shape`), transliterated from
 * ooxmlsdk `ShapeValues`. Bar3D/Column3D charts only.
 */
export type Bar3DShape = "cone" | "coneToMax" | "box" | "cylinder" | "pyramid" | "pyramidToMax";
