// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderLinePatch } from "./BorderLinePatch.js";

export type BorderPatch = { all?: BorderLinePatch, left?: BorderLinePatch, right?: BorderLinePatch, top?: BorderLinePatch, bottom?: BorderLinePatch, };
