// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderLinePatch } from "./BorderLinePatch.js";

/**
 * Cell border edges. `all` is sugar applied to every side.
 *
 * schema-excluded: xmlns, xmlOtherAttrs, outline, start, end, vertical, horizontal
 */
export type BorderPatch = {
  all?: BorderLinePatch;
  left?: BorderLinePatch;
  right?: BorderLinePatch;
  top?: BorderLinePatch;
  bottom?: BorderLinePatch;
  diagonal?: BorderLinePatch;
  diagonalUp?: boolean;
  diagonalDown?: boolean;
};
