// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderLineStyle } from "./BorderLineStyle.js";

export type BorderLinePatch = { style: BorderLineStyle; color?: string };
