// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in axis display-unit scale (`c:builtInUnit`, OOXML `ST_BuiltInUnit`).
 *
 * Each variant divides the value-axis labels by its power of ten (e.g. `Millions`
 * shows `5` for `5_000_000`). The xlsx-preview renderer applies the factor to the
 * tick labels and draws the unit name as a label band.
 */
export type BuiltInUnit = "hundreds" | "thousands" | "tenThousands" | "hundredThousands" | "millions" | "tenMillions" | "hundredMillions" | "billions" | "trillions";
