// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalcMode } from "./CalcMode.js";

export type CalcProperties = { calcMode?: CalcMode, fullCalcOnLoad?: boolean, forceFullCalc?: boolean, calcOnSave?: boolean, concurrentCalc?: boolean, iterate?: boolean, iterateCount?: number, iterateDelta?: number, fullPrecision?: boolean, calculationId?: number, };
