// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCellValue } from "./ApiCellValue.js";
import type { RichText } from "./RichText.js";

export type CellInfo = {
  sheet: string;
  reference: string;
  row: number;
  column: number;
  value: ApiCellValue;
  formula?: string;
  styleIndex?: number;
  richText?: RichText;
};
