// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CfIconSetKind =
  | "threeArrows"
  | "threeArrowsGray"
  | "threeFlags"
  | "threeTrafficLights1"
  | "threeTrafficLights2"
  | "threeSigns"
  | "threeSymbols"
  | "threeSymbols2"
  | "fourArrows"
  | "fourArrowsGray"
  | "fourRedToBlack"
  | "fourRating"
  | "fourTrafficLights"
  | "fiveArrows"
  | "fiveArrowsGray"
  | "fiveRating"
  | "fiveQuarters";
