// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CfRuleKind = "expression" | "cellIs" | "top10" | "duplicateValues" | "uniqueValues" | "containsText" | "notContainsText" | "beginsWith" | "endsWith" | "containsBlanks" | "notContainsBlanks" | "containsErrors" | "notContainsErrors" | "timePeriod" | "aboveAverage" | "colorScale" | "dataBar" | "iconSet";
