// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfValueObjectKind } from "./CfValueObjectKind.js";

export type CfValueObject = { kind: CfValueObjectKind; value?: string };
