// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the second plot's slices are split out (`c:splitType/@val`, OOXML
 * `ST_SplitType`), transliterated from ooxmlsdk `SplitValues`. ofPie charts
 * only. The SDK omits the schema's `auto` default, so it is not modeled.
 */
export type ChartSplitType = "cust" | "percent" | "pos" | "val";
