// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single data point override (`c:dPt`), distilled from ooxmlsdk `DataPoint`.
 *
 * Per-point `fill` and `explosion` are modeled. The xlsx-preview renderer
 * reads `fill` for bar/column/pie/doughnut series (e.g. the waterfall-via-noFill
 * idiom) and `explosion` for pie/doughnut slice offset.
 * Intentionally not modeled (preserved on update, author via raw XML):
 * `invertIfNegative`, per-point `marker`, `bubble3D`,
 * non-solid `spPr` styling, `pictureOptions`, `extLst`.
 *
 * schema-excluded: invertIfNegative, marker, bubble3D, pictureOptions
 */
export type ChartDataPoint = {
  /**
   * `c:idx/@val`; 0-based data-point index within the series.
   */
  index: number;
  /**
   * `c:spPr` solid fill: 6-hex `RRGGBB` / 8-hex `AARRGGBB`, or the literal
   * `"none"` for an explicit no-fill (`a:noFill`).
   */
  fill?: string;
  /**
   * `c:explosion/@val`; pie/doughnut slice offset as a percent of radius
   * (0..=400). Renderer-visible for pie/doughnut charts.
   */
  explosion?: number;
};
