// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text run styling (`c:txPr/a:p/a:pPr/a:defRPr`), distilled from ooxmlsdk
 * `DefaultRunProperties`. Used for the legend font.
 *
 * Round-trips for Excel; the xlsx-preview renderer draws chart text with its
 * own built-in fonts.
 *
 * Intentionally not modeled (preserved on update, author via raw XML):
 * underline, strike, kerning, caps, baseline, east-asian/complex/symbol fonts,
 * outline, hyperlinks, `extLst`.
 *
 * schema-excluded: kumimoji, lang, altLang, u, strike, kern, cap, spc,
 * normalizeH, baseline, noProof, dirty, err, smtClean, smtId, bmk, ln,
 * effectLst, highlight, uLnTx, uFillTx, ea, cs, sym, hlinkClick,
 * hlinkMouseOver, rtl
 */
export type ChartTextStyle = { 
/**
 * `a:defRPr/@sz` in whole points (1..=4000); stored as 100ths of a point.
 */
size?: number, 
/**
 * `a:defRPr/@b`.
 */
bold?: boolean, 
/**
 * `a:defRPr/@i`.
 */
italic?: boolean, 
/**
 * `a:defRPr/a:solidFill` color: 6-hex `RRGGBB` / 8-hex `AARRGGBB`.
 */
color?: string, 
/**
 * `a:defRPr/a:latin/@typeface`; font family name.
 */
typeface?: string, };
