// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartKind = "column" | "bar" | "line" | "pie" | "area" | "scatter" | "bubble" | "doughnut" | "radar" | "stock" | "column3d" | "bar3d" | "line3d" | "pie3d" | "area3d" | "surface3d" | "surface" | "pieofpie" | "barofpie";
