// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two-cell anchor for a chart or image, in OOXML `xdr:twoCellAnchor` coordinates.
 *
 * All row/column indices are **0-based** (column A = 0, row 1 = 0), matching the
 * underlying `<xdr:col>` / `<xdr:row>` elements. The anchor's bottom-right corner
 * is the top-left of the cell at `(to_column, to_row)` plus any EMU offsets, so
 * to span columns A..=E inclusive use `from_column: 0, to_column: 5`.
 */
export type ChartAnchor = { 
/**
 * 0-based column index of the top-left anchor cell (A = 0).
 */
fromColumn: number, 
/**
 * 0-based row index of the top-left anchor cell (row 1 = 0).
 */
fromRow: number, 
/**
 * 0-based column index of the bottom-right anchor cell (exclusive of any offset).
 */
toColumn: number, 
/**
 * 0-based row index of the bottom-right anchor cell (exclusive of any offset).
 */
toRow: number, fromColumnOffsetEmu?: bigint, fromRowOffsetEmu?: bigint, toColumnOffsetEmu?: bigint, toRowOffsetEmu?: bigint, };
