// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSpec } from "./AnchorSpec.js";

/**
 * In-place update for a chartEx chart. Only drawing-anchor and name are
 * editable; the `cx:chartSpace` part itself is left untouched.
 */
export type ChartExUpdate = { name?: string; anchor?: AnchorSpec };
