// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAxisGroup } from "./ChartAxisGroup.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartDataPoint } from "./ChartDataPoint.js";
import type { ChartKind } from "./ChartKind.js";
import type { ChartLine } from "./ChartLine.js";
import type { ChartMarker } from "./ChartMarker.js";

export type ChartSeriesPatch = {
  name?: string;
  nameRef?: string;
  valuesRef: string;
  xValuesRef?: string;
  bubbleSizesRef?: string;
  color?: string;
  dataLabels?: ChartDataLabels;
  /**
   * `c:marker`; line/scatter series only.
   */
  marker?: ChartMarker;
  /**
   * Connecting-line / outline styling (`spPr/a:ln`): width, dash, hidden.
   */
  line?: ChartLine;
  /**
   * Smooth the connecting line with a spline (`c:smooth`); line/scatter series
   * only. On a scatter chart any smoothed series sets the chart's
   * `c:scatterStyle` to `smoothMarker`, which the xlsx-preview renderer draws
   * as curved.
   */
  smooth?: boolean;
  /**
   * Per-data-point fill overrides (`c:dPt`). Each entry recolors one point by
   * index; use `fill: "none"` for the waterfall-via-noFill idiom.
   */
  dataPoints?: Array<ChartDataPoint>;
  /**
   * Per-series chart type, overriding the chart's `kind` to build a combo
   * chart. Only `Column`/`Bar`/`Line`/`Area` are valid here; mixing those on
   * one chart emits multiple `c:barChart`/`c:lineChart`/`c:areaChart` groups.
   */
  kind?: ChartKind;
  /**
   * Plot this series on the primary or secondary value axis. `Secondary`
   * synthesizes a right-hand `c:valAx`. Combo/cartesian charts only.
   */
  axis?: ChartAxisGroup;
  /**
   * Flip the fill color for negative values (`c:invertIfNegative`); bar/column
   * and bubble series only. Round-trips for Excel.
   */
  invertIfNegative?: boolean;
};
