// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartLine } from "./ChartLine.js";

/**
 * Plot-area background styling (`c:plotArea/c:spPr`), distilled from ooxmlsdk
 * `PlotArea`.
 *
 * Round-trips for Excel; the xlsx-preview renderer draws the plot area with a
 * white background regardless.
 *
 * schema-excluded: layout, plot charts, axes, dTable, extLst
 */
export type ChartPlotArea = {
  /**
   * `c:spPr` solid fill: 6-hex `RRGGBB` / 8-hex `AARRGGBB`, or the literal
   * `"none"` for an explicit no-fill (`a:noFill`).
   */
  fill?: string;
  /**
   * `c:spPr/a:ln` border styling (width, dash, hidden).
   */
  border?: ChartLine;
};
