// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A modern "chartEx" chart layout (`cx:series/@layoutId`, OOXML `ST_SeriesLayout`),
 * transliterated from ooxmlsdk `SeriesLayout`. These charts live in a separate
 * `chartEx{N}.xml` part (`cx:` namespace) referenced from the drawing, distinct
 * from the legacy `c:` charts authored via {@link ChartPatch}.
 *
 * `histogram` and `pareto` are authored as `clusteredColumn` / `paretoLine`
 * series under the hood; this enum collapses those to the user-facing layout.
 * All eight are renderer-visible in xlsx-preview.
 */
export type ChartExKind =
  | "waterfall"
  | "funnel"
  | "treemap"
  | "sunburst"
  | "histogram"
  | "pareto"
  | "boxWhisker"
  | "regionMap";
