// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartLegendPosition = "right" | "left" | "top" | "bottom" | "top_right" | "none";
