// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSpec } from "./AnchorSpec.js";
import type { ChartAxisPatch } from "./ChartAxisPatch.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartLegendPosition } from "./ChartLegendPosition.js";
import type { ChartSeriesPatch } from "./ChartSeriesPatch.js";
import type { ChartStacking } from "./ChartStacking.js";
import type { DispBlanksAs } from "./DispBlanksAs.js";
import type { RadarStyle } from "./RadarStyle.js";

export type ChartUpdate = {
  name?: string;
  title?: string;
  legendPosition?: ChartLegendPosition;
  categoriesRef?: string;
  series?: Array<ChartSeriesPatch>;
  anchor?: AnchorSpec;
  categoryAxisTitle?: string;
  valueAxisTitle?: string;
  categoryAxis?: ChartAxisPatch;
  valueAxis?: ChartAxisPatch;
  stacking?: ChartStacking;
  /**
   * `c:gapWidth` (0..=500); bar/column charts only.
   */
  gapWidth?: number;
  /**
   * `c:overlap` (-100..=100); bar/column charts only.
   */
  overlap?: number;
  /**
   * `c:radarStyle`; radar charts only.
   */
  radarStyle?: RadarStyle;
  /**
   * `c:holeSize` (10..=90); doughnut charts only.
   */
  holeSize?: number;
  /**
   * `c:firstSliceAng` (0..=360); pie/doughnut charts only.
   */
  firstSliceAngle?: number;
  /**
   * `c:hiLowLines`; stock charts only. Vertical line spanning each category's
   * high/low values. Defaults to `true` when omitted.
   */
  hiLowLines?: boolean;
  /**
   * `c:upDownBars`; stock charts only. Open/close bars (white up, black down).
   * Defaults to `true` for open-high-low-close (4+ series).
   */
  upDownBars?: boolean;
  /**
   * `c:dropLines`; stock charts only. Vertical line from each point to the
   * category axis. Defaults to `false` when omitted.
   */
  dropLines?: boolean;
  /**
   * `c:dispBlanksAs`; how blank source cells are plotted. Defaults to `Gap`.
   */
  dispBlanksAs?: DispBlanksAs;
  dataLabels?: ChartDataLabels;
};
