// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Box-and-whisker quartile calculation method (`cx:statistics/@quartileMethod`,
 * OOXML `ST_QuartileMethod`), transliterated from ooxmlsdk `QuartileMethod`.
 * Round-trips for Excel; the xlsx-preview renderer always uses inclusive quartiles.
 */
export type ChartExQuartileMethod = "inclusive" | "exclusive";
