// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which value axis a series is plotted against in a combo chart.
 *
 * `Secondary` puts the series on a second value axis (`c:valAx` at the right of
 * the plot area), the standard idiom for charts mixing series at different
 * scales (e.g. revenue bars + margin-% line).
 */
export type ChartAxisGroup = "primary" | "secondary";
