// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartLine } from "./ChartLine.js";

/**
 * 3D wall/floor surface styling (`c:floor`/`c:sideWall`/`c:backWall` →
 * `c:spPr`), distilled from ooxmlsdk `Floor`/`SideWall`/`BackWall` (all
 * `CT_Surface`). 3D chart kinds only.
 *
 * Round-trips for Excel; the xlsx-preview renderer draws 3D charts flat (no
 * walls/floor).
 *
 * schema-excluded: thickness, pictureOptions, extLst
 */
export type ChartSurfaceWall = {
  /**
   * `c:spPr` solid fill: 6-hex `RRGGBB` / 8-hex `AARRGGBB`, or the literal
   * `"none"` for an explicit no-fill (`a:noFill`).
   */
  fill?: string;
  /**
   * `c:spPr/a:ln` border styling (width, dash, hidden).
   */
  border?: ChartLine;
};
