// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartAnchor = {
  fromColumn: number;
  fromRow: number;
  toColumn: number;
  toRow: number;
  fromColumnOffsetEmu?: bigint;
  fromRowOffsetEmu?: bigint;
  toColumnOffsetEmu?: bigint;
  toRowOffsetEmu?: bigint;
};
