// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartErrorBarType } from "./ChartErrorBarType.js";
import type { ChartErrorDirection } from "./ChartErrorDirection.js";
import type { ChartErrorValueType } from "./ChartErrorValueType.js";

/**
 * Series error bars (`c:errBars`), distilled from ooxmlsdk `ErrorBars`.
 *
 * Supported on bar/column, line, area, scatter and bubble series only (Excel
 * disallows error bars on pie/doughnut/radar/stock). `value` carries the
 * magnitude for `FixedValue`/`Percentage` and the multiplier for
 * `StandardDeviation`/`StandardError`; `plusRef`/`minusRef` (range formulas) or
 * `plusValues`/`minusValues` (inline literals) carry per-point magnitudes for
 * `Custom`. Round-trips for Excel; the xlsx-preview renderer does not draw
 * error bars.
 *
 * Intentionally not modeled (preserved on update, author via raw XML): `spPr`
 * line styling, numbering caches, `extLst`.
 *
 * schema-excluded: spPr
 */
export type ChartErrorBars = { 
/**
 * `c:errDir/@val`; the axis the bars run along. Omitted (Excel default) for
 * bar/column/line/area; set `Y` (and a second `X` set) for scatter/bubble.
 */
direction?: ChartErrorDirection, 
/**
 * `c:errBarType/@val`; which sides the bars extend.
 */
barType: ChartErrorBarType, 
/**
 * `c:errValType/@val`; how magnitudes are computed.
 */
valueType: ChartErrorValueType, 
/**
 * `c:val/@val`; magnitude (fixed/percentage) or multiplier (stdDev/stdErr).
 */
value?: number, 
/**
 * `c:noEndCap/@val`; draw the bars without end caps (T-less).
 */
noEndCap?: boolean, 
/**
 * `c:plus` as a range formula (`numRef`); custom positive magnitudes.
 */
plusRef?: string, 
/**
 * `c:minus` as a range formula (`numRef`); custom negative magnitudes.
 */
minusRef?: string, 
/**
 * `c:plus` as inline literals (`numLit`); custom positive magnitudes.
 */
plusValues?: Array<number>, 
/**
 * `c:minus` as inline literals (`numLit`); custom negative magnitudes.
 */
minusValues?: Array<number>, };
