// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How error-bar magnitudes are computed (`c:errValType/@val`, OOXML
 * `ST_ErrValType`), transliterated from ooxmlsdk `ErrorValues`.
 */
export type ChartErrorValueType = "cust" | "fixedVal" | "percentage" | "stdDev" | "stdErr";
