// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartLegendPosition } from "./ChartLegendPosition.js";
import type { ChartSeriesPatch } from "./ChartSeriesPatch.js";
import type { ChartStacking } from "./ChartStacking.js";

export type ChartUpdate = {
  name?: string;
  title?: string;
  legendPosition?: ChartLegendPosition;
  categoriesRef?: string;
  series?: Array<ChartSeriesPatch>;
  anchor?: ChartAnchor;
  categoryAxisTitle?: string;
  valueAxisTitle?: string;
  stacking?: ChartStacking;
  dataLabels?: ChartDataLabels;
};
