// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartDataLabelPosition } from "./ChartDataLabelPosition.js";

/**
 * A single per-point data label (`c:dLbl`) inside `c:dLbls`.
 *
 * `index` is the 0-based data-point this label applies to. Set `delete: true`
 * to suppress that point's label entirely (all other fields ignored). Otherwise
 * any set field overrides the series-level `ChartDataLabels` for this point only.
 *
 * schema-excluded: layout (manual position), tx (rich-text override), spPr
 * (label shape/fill), txPr (label font), showBubbleSize, extLst.
 */
export type ChartDataLabel = { 
/**
 * 0-based data-point index this override applies to (`c:idx/@val`).
 */
index: number, 
/**
 * Suppress this point's label (`c:delete`). When `true`, all other fields
 * are ignored.
 */
delete: boolean, showValue?: boolean, showCategoryName?: boolean, showSeriesName?: boolean, showPercent?: boolean, showLegendKey?: boolean, position?: ChartDataLabelPosition, separator?: string, 
/**
 * `c:numFmt/@formatCode`; number format applied to this point's value.
 */
numberFormat?: string, };
