// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single data point override (`c:dPt`), distilled from ooxmlsdk `DataPoint`.
 *
 * Currently only per-point fill is modeled, which the xlsx-preview renderer
 * reads for bar/column/pie/doughnut series (e.g. the waterfall-via-noFill idiom).
 * Intentionally not modeled (preserved on update, author via raw XML):
 * `invertIfNegative`, per-point `marker`, `bubble3D`, `explosion`,
 * non-solid `spPr` styling, `pictureOptions`, `extLst`.
 */
export type ChartDataPoint = {
  /**
   * `c:idx/@val`; 0-based data-point index within the series.
   */
  index: number;
  /**
   * `c:spPr` solid fill: 6-hex `RRGGBB` / 8-hex `AARRGGBB`, or the literal
   * `"none"` for an explicit no-fill (`a:noFill`).
   */
  fill?: string;
};
