// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a manual-layout coordinate is interpreted (`c:xMode`/`yMode`/`wMode`/
 * `hMode` `@val`, OOXML `ST_LayoutMode`), transliterated from ooxmlsdk
 * `LayoutModeValues`. `edge` = absolute position from the chart edge; `factor`
 * = offset relative to the default position.
 */
export type ChartLayoutMode = "edge" | "factor";
