// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which sides the error bars extend (`c:errBarType/@val`, OOXML `ST_ErrBarType`),
 * transliterated from ooxmlsdk `ErrorBarValues`.
 */
export type ChartErrorBarType = "both" | "minus" | "plus";
