// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Manual-layout anchor target (`c:layoutTarget/@val`, OOXML `ST_LayoutTarget`),
 * transliterated from ooxmlsdk `LayoutTargetValues`. Plot area only: `inner`
 * excludes axis labels, `outer` includes them.
 */
export type ChartLayoutTarget = "inner" | "outer";
