// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineDash } from "./LineDash.js";

/**
 * Series connecting-line / outline styling (`spPr/a:ln`), distilled from
 * ooxmlsdk `Outline`.
 *
 * On line/scatter/radar series this is the connecting line; on bar/area/pie
 * series it is the shape outline. `width`/`dash` are renderer-visible. Setting
 * `none: true` emits `a:ln/a:noFill` (hidden line, markers-only) and overrides
 * `width`/`dash`.
 *
 * Intentionally not modeled (preserved on update, author via raw XML): `cap`,
 * `cmpd`, `algn`, `custDash`, line joins, head/tail ends, gradient/pattern
 * line fills, `extLst`.
 */
export type ChartLine = { 
/**
 * `a:ln/@w` in EMU (1 pt = 12700 EMU, 0..=20116800).
 */
widthEmu?: number, 
/**
 * `a:ln/a:prstDash/@val`.
 */
dash?: LineDash, 
/**
 * Hide the line (`a:ln/a:noFill`); markers-only. Overrides `width`/`dash`.
 */
none?: boolean, };
