// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 3D view settings (`c:view3D`), distilled from ooxmlsdk `View3D`. Applies to
 * any 3D chart kind (bar3D/column3D/line3D/pie3D/area3D). Round-trips for
 * Excel; the xlsx-preview renderer draws 3D charts flat (no rotation/depth).
 *
 * schema-excluded: extLst
 */
export type ChartView3D = { 
/**
 * `c:rotX/@val` (-90..=90); rotation about the x-axis in degrees.
 */
rotX?: number, 
/**
 * `c:rotY/@val` (0..=360); rotation about the y-axis in degrees.
 */
rotY?: number, 
/**
 * `c:perspective/@val` (0..=240); perspective distance. Ignored when
 * `right_angle_axes` is `true`.
 */
perspective?: number, 
/**
 * `c:rAngAx/@val`; render axes at right angles (no perspective).
 */
rightAngleAxes?: boolean, 
/**
 * `c:depthPercent/@val` (20..=2000); depth of the plot as a percent of width.
 */
depthPercent?: number, 
/**
 * `c:hPercent/@val` (5..=500); height of the plot as a percent of width.
 */
heightPercent?: number, };
