// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bar3DShape } from "./Bar3DShape.js";
import type { ChartAnchor } from "./ChartAnchor.js";
import type { ChartAxisPatch } from "./ChartAxisPatch.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartDataTable } from "./ChartDataTable.js";
import type { ChartKind } from "./ChartKind.js";
import type { ChartLegendPosition } from "./ChartLegendPosition.js";
import type { ChartSeriesInfo } from "./ChartSeriesInfo.js";
import type { ChartStacking } from "./ChartStacking.js";
import type { ChartView3D } from "./ChartView3D.js";
import type { DispBlanksAs } from "./DispBlanksAs.js";
import type { RadarStyle } from "./RadarStyle.js";

export type ChartInfo = {
  sheet: string;
  id: string;
  name: string;
  kind: ChartKind;
  title?: string;
  legendPosition?: ChartLegendPosition;
  categoriesRef?: string;
  series: Array<ChartSeriesInfo>;
  anchor: ChartAnchor;
  categoryAxisTitle?: string;
  valueAxisTitle?: string;
  categoryAxis?: ChartAxisPatch;
  valueAxis?: ChartAxisPatch;
  stacking?: ChartStacking;
  /**
   * `c:gapWidth` (0..=500); bar/column charts only.
   */
  gapWidth?: number;
  /**
   * `c:overlap` (-100..=100); bar/column charts only.
   */
  overlap?: number;
  /**
   * `c:radarStyle`; radar charts only.
   */
  radarStyle?: RadarStyle;
  /**
   * `c:holeSize` (10..=90); doughnut charts only.
   */
  holeSize?: number;
  /**
   * `c:firstSliceAng` (0..=360); pie/doughnut charts only.
   */
  firstSliceAngle?: number;
  /**
   * `c:hiLowLines`; stock charts only. Vertical line spanning each category's
   * high/low values. Defaults to `true` when omitted.
   */
  hiLowLines?: boolean;
  /**
   * `c:upDownBars`; stock charts only. Open/close bars (white up, black down).
   * Defaults to `true` for open-high-low-close (4+ series).
   */
  upDownBars?: boolean;
  /**
   * `c:dropLines`; stock charts only. Vertical line from each point to the
   * category axis. Defaults to `false` when omitted.
   */
  dropLines?: boolean;
  /**
   * `c:dispBlanksAs`; how blank source cells are plotted. Defaults to `Gap`.
   */
  dispBlanksAs?: DispBlanksAs;
  /**
   * `c:varyColors`; color each data point (or each series) differently. Excel
   * defaults pie/doughnut/bubble charts to `true` and others to `false`.
   */
  varyColors?: boolean;
  dataLabels?: ChartDataLabels;
  /**
   * `c:dTable`; data table beneath the plot. Cartesian charts only.
   */
  dataTable?: ChartDataTable;
  /**
   * `c:view3D`; 3D view settings. 3D chart kinds only.
   */
  view3d?: ChartView3D;
  /**
   * `c:shape`; bar/column 3D shape. Bar3D/Column3D charts only.
   */
  barShape?: Bar3DShape;
};
