// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSpec } from "./AnchorSpec.js";
import type { ChartAxisPatch } from "./ChartAxisPatch.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartKind } from "./ChartKind.js";
import type { ChartLegendPosition } from "./ChartLegendPosition.js";
import type { ChartSeriesPatch } from "./ChartSeriesPatch.js";
import type { ChartStacking } from "./ChartStacking.js";
import type { RadarStyle } from "./RadarStyle.js";

export type ChartPatch = { name?: string, kind: ChartKind, title?: string, legendPosition?: ChartLegendPosition, categoriesRef?: string, series: Array<ChartSeriesPatch>, anchor: AnchorSpec, categoryAxisTitle?: string, valueAxisTitle?: string, categoryAxis?: ChartAxisPatch, valueAxis?: ChartAxisPatch, stacking?: ChartStacking, 
/**
 * `c:gapWidth` (0..=500); bar/column charts only. Space between bar clusters
 * as a percentage of bar width.
 */
gapWidth?: number, 
/**
 * `c:overlap` (-100..=100); bar/column charts only. Stacked charts force 100.
 */
overlap?: number, 
/**
 * `c:radarStyle`; radar charts only. Defaults to `Standard` when omitted.
 */
radarStyle?: RadarStyle, dataLabels?: ChartDataLabels, };
