// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartKind } from "./ChartKind.js";
import type { ChartLegendPosition } from "./ChartLegendPosition.js";
import type { ChartSeriesInfo } from "./ChartSeriesInfo.js";
import type { ChartStacking } from "./ChartStacking.js";

export type ChartInfo = {
  sheet: string;
  id: string;
  name: string;
  kind: ChartKind;
  title?: string;
  legendPosition?: ChartLegendPosition;
  categoriesRef?: string;
  series: Array<ChartSeriesInfo>;
  anchor: ChartAnchor;
  categoryAxisTitle?: string;
  valueAxisTitle?: string;
  stacking?: ChartStacking;
  dataLabels?: ChartDataLabels;
};
