// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrendlineKind } from "./TrendlineKind.js";

/**
 * A series trendline (`c:trendline`), distilled from ooxmlsdk `Trendline`.
 *
 * Supported on bar/column, line, area, scatter and bubble series only (Excel
 * disallows trendlines on pie/doughnut/radar/stock). `polynomial_order` applies
 * to `Polynomial`, `period` to `MovingAverage`; `intercept` to
 * exp/linear/poly/power. Round-trips for Excel; the xlsx-preview renderer does
 * not draw trendlines.
 *
 * Intentionally not modeled (preserved on update, author via raw XML): `spPr`
 * line styling, `trendlineLbl` label text/layout, `extLst`.
 *
 * schema-excluded: spPr, trendlineLbl
 */
export type ChartTrendline = {
  /**
   * `c:trendlineType/@val`.
   */
  type: TrendlineKind;
  /**
   * `c:name`; custom trendline label name overriding Excel's auto label.
   */
  name?: string;
  /**
   * `c:order/@val` (2..=6); polynomial trendlines only.
   */
  polynomialOrder?: number;
  /**
   * `c:period/@val` (>=2); moving-average trendlines only.
   */
  period?: number;
  /**
   * `c:forward/@val`; periods to project forward.
   */
  forward?: number;
  /**
   * `c:backward/@val`; periods to project backward.
   */
  backward?: number;
  /**
   * `c:intercept/@val`; forced y-intercept.
   */
  intercept?: number;
  /**
   * `c:dispEq/@val`; show the regression equation on the chart.
   */
  displayEquation?: boolean;
  /**
   * `c:dispRSqr/@val`; show the R² value on the chart.
   */
  displayRSquared?: boolean;
};
