// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAxisGroup } from "./ChartAxisGroup.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartKind } from "./ChartKind.js";
import type { ChartMarker } from "./ChartMarker.js";

export type ChartSeriesPatch = { name?: string, nameRef?: string, valuesRef: string, xValuesRef?: string, bubbleSizesRef?: string, color?: string, dataLabels?: ChartDataLabels, 
/**
 * `c:marker`; line/scatter series only.
 */
marker?: ChartMarker, 
/**
 * Per-series chart type, overriding the chart's `kind` to build a combo
 * chart. Only `Column`/`Bar`/`Line`/`Area` are valid here; mixing those on
 * one chart emits multiple `c:barChart`/`c:lineChart`/`c:areaChart` groups.
 */
kind?: ChartKind, 
/**
 * Plot this series on the primary or secondary value axis. `Secondary`
 * synthesizes a right-hand `c:valAx`. Combo/cartesian charts only.
 */
axis?: ChartAxisGroup, };
