// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chartEx data series (`cx:series`), distilled from ooxmlsdk `Series`.
 *
 * `values_ref` is the `cx:numDim` formula (typically a sheet range like
 * `Sheet1!$B$2:$B$7`); its dimension type is derived from the parent chart's
 * kind (`val` for waterfall/funnel/histogram/pareto/boxWhisker, `size` for
 * treemap/sunburst, `colorVal` for regionMap). `name`/`name_ref` populate
 * `cx:tx`. Most kinds take a single series; `boxWhisker` accepts several.
 *
 * schema-excluded: spPr, valueColors, valueColorPositions, dataPt, dataLabels,
 * hidden, ownerIdx, uniqueId, formatIdx, axisId, extLst
 */
export type ChartExSeriesPatch = { name?: string, nameRef?: string, valuesRef: string, };
