// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAxisGroup } from "./ChartAxisGroup.js";
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartDataPoint } from "./ChartDataPoint.js";
import type { ChartKind } from "./ChartKind.js";
import type { ChartLine } from "./ChartLine.js";
import type { ChartMarker } from "./ChartMarker.js";

export type ChartSeriesInfo = {
  name?: string;
  nameRef?: string;
  valuesRef: string;
  xValuesRef?: string;
  bubbleSizesRef?: string;
  color?: string;
  dataLabels?: ChartDataLabels;
  /**
   * `c:marker`; line/scatter series only.
   */
  marker?: ChartMarker;
  /**
   * Connecting-line / outline styling; see {@link ChartSeriesPatch.line}.
   */
  line?: ChartLine;
  /**
   * Spline-smoothed line (`c:smooth`); see {@link ChartSeriesPatch.smooth}.
   */
  smooth?: boolean;
  /**
   * Per-data-point fill overrides (`c:dPt`); see {@link ChartSeriesPatch.dataPoints}.
   */
  dataPoints?: Array<ChartDataPoint>;
  /**
   * Per-series chart type for combo charts; see {@link ChartSeriesPatch.kind}.
   */
  kind?: ChartKind;
  /**
   * Primary/secondary value-axis group; see {@link ChartSeriesPatch.axis}.
   */
  axis?: ChartAxisGroup;
  /**
   * Negative-value fill flip; see {@link ChartSeriesPatch.invertIfNegative}.
   */
  invertIfNegative?: boolean;
};
