// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chart data table (`c:dTable` in `c:plotArea`), distilled from ooxmlsdk
 * `DataTable`.
 *
 * A grid of the source values drawn beneath a cartesian plot. Cartesian charts
 * only (column/bar/line/area); Excel rejects data tables on
 * pie/doughnut/scatter/bubble/radar/stock. Round-trips for Excel; the
 * xlsx-preview renderer does not draw the data table.
 *
 * Intentionally not modeled (preserved on update, author via raw XML): `spPr`
 * shape/border styling, `txPr` font, `extLst`.
 *
 * schema-excluded: spPr, txPr
 */
export type ChartDataTable = { 
/**
 * `c:showHorzBorder/@val`; draw horizontal cell borders.
 */
showHorizontalBorder?: boolean, 
/**
 * `c:showVertBorder/@val`; draw vertical cell borders.
 */
showVerticalBorder?: boolean, 
/**
 * `c:showOutline/@val`; draw the table's outline border.
 */
showOutline?: boolean, 
/**
 * `c:showKeys/@val`; show the series legend keys in the first column.
 */
showKeys?: boolean, };
