// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartLine } from "./ChartLine.js";
import type { ChartTextStyle } from "./ChartTextStyle.js";

/**
 * Legend background/border (`c:legend/c:spPr`) and font (`c:legend/c:txPr`),
 * distilled from ooxmlsdk `Legend`. The legend position is set separately via
 * {@link ChartPatch.legendPosition}.
 *
 * Round-trips for Excel; the xlsx-preview renderer draws the legend with its
 * own built-in styling.
 *
 * schema-excluded: legendPos, legendEntry, layout, overlay, extLst
 */
export type ChartLegend = {
  /**
   * `c:spPr` solid fill: 6-hex `RRGGBB` / 8-hex `AARRGGBB`, or the literal
   * `"none"` for an explicit no-fill (`a:noFill`).
   */
  fill?: string;
  /**
   * `c:spPr/a:ln` border styling (width, dash, hidden).
   */
  border?: ChartLine;
  /**
   * `c:txPr/a:p/a:pPr/a:defRPr` legend text font.
   */
  font?: ChartTextStyle;
};
