// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the chart's legend sits relative to the plot area.
 *
 * Use `None` to suppress the legend entirely (Excel UI: "No Legend"). `TopRight`
 * corresponds to Excel's "Overlay Legend at Right" position.
 */
export type ChartLegendPosition = "right" | "left" | "top" | "bottom" | "top_right" | "none";
