// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartDataLabelPosition =
  | "center"
  | "inside_end"
  | "inside_base"
  | "outside_end"
  | "top"
  | "bottom"
  | "left"
  | "right"
  | "best_fit";
