// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartDataLabels } from "./ChartDataLabels.js";
import type { ChartMarker } from "./ChartMarker.js";

export type ChartSeriesInfo = {
  name?: string;
  nameRef?: string;
  valuesRef: string;
  xValuesRef?: string;
  bubbleSizesRef?: string;
  color?: string;
  dataLabels?: ChartDataLabels;
  /**
   * `c:marker`; line/scatter series only.
   */
  marker?: ChartMarker;
};
