// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarkerStyle } from "./MarkerStyle.js";

/**
 * Series data-point marker (`c:marker`), distilled from ooxmlsdk `Marker`.
 *
 * Intentionally not modeled (preserved on update, author via raw XML):
 * `spPr` styling, `pictureOptions`, `extLst`.
 *
 * schema-excluded: xmlns, spPr
 */
export type ChartMarker = { 
/**
 * `c:symbol/@val`.
 */
style?: MarkerStyle, 
/**
 * `c:size/@val` (2..=72).
 */
size?: number, };
