// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartGradientStop } from "./ChartGradientStop.js";

/**
 * A DrawingML gradient fill (`a:gradFill`) for a chart data point, distilled
 * from ooxmlsdk `GradientFill`. Linear gradients only.
 *
 * schema-excluded: flip, rotWithShape, tileRect, path
 */
export type ChartGradientFill = {
  /**
   * `a:gsLst/a:gs` stops (in document order). At least two are expected.
   */
  stops: Array<ChartGradientStop>;
  /**
   * `a:lin/@ang` linear-gradient angle in degrees (clockwise). Defaults to 0
   * (left-to-right) when omitted.
   */
  angle?: number;
};
