// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartDataLabelPosition } from "./ChartDataLabelPosition.js";

export type ChartDataLabels = { showValue?: boolean, showCategoryName?: boolean, showSeriesName?: boolean, showPercent?: boolean, showLegendKey?: boolean, position?: ChartDataLabelPosition, separator?: string, };
