// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single gradient stop (`a:gs`), distilled from ooxmlsdk `GradientStop`.
 */
export type ChartGradientStop = {
  /**
   * `a:gs/@pos` as a percent (0..=100), emitted in 1000ths of a percent.
   */
  position: number;
  /**
   * `a:srgbClr/@val`: 6-hex `RRGGBB` / 8-hex `AARRGGBB`.
   */
  color: string;
};
