// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";
import type { ChartExKind } from "./ChartExKind.js";
import type { ChartExQuartileMethod } from "./ChartExQuartileMethod.js";
import type { ChartExSeriesInfo } from "./ChartExSeriesInfo.js";
import type { ChartLegendPosition } from "./ChartLegendPosition.js";

/**
 * A modern chartEx chart as read back from `chartEx{N}.xml`.
 */
export type ChartExInfo = {
  sheet: string;
  id: string;
  name: string;
  kind: ChartExKind;
  title?: string;
  anchor: ChartAnchor;
  categoriesRef?: string;
  series: Array<ChartExSeriesInfo>;
  legendPosition?: ChartLegendPosition;
  subtotals: Array<number>;
  binCount?: number;
  binSize?: number;
  quartileMethod?: ChartExQuartileMethod;
};
