// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error-bar axis direction (`c:errDir/@val`, OOXML `ST_ErrDir`), transliterated
 * from ooxmlsdk `ErrorBarDirectionValues`.
 */
export type ChartErrorDirection = "x" | "y";
