// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfValueObject } from "./CfValueObject.js";

export type ColorScalePatch = { values: Array<CfValueObject>, colors: Array<string>, };
