// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommentInfo = { sheet: string, reference: string, row: number, column: number, author: string, text: string, };
