// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the value axis crosses between categories or at their midpoints
 * (`c:crossBetween`, OOXML `ST_CrossBetween`).
 */
export type CrossBetween = "between" | "midpointCategory";
