// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataValidationErrorStyle } from "./DataValidationErrorStyle.js";
import type { DataValidationOperator } from "./DataValidationOperator.js";
import type { DataValidationType } from "./DataValidationType.js";

export type DataValidationPatch = { ruleType: DataValidationType, operator?: DataValidationOperator, allowBlank?: boolean, showDropDown?: boolean, showInputMessage?: boolean, showErrorMessage?: boolean, errorStyle?: DataValidationErrorStyle, errorTitle?: string, error?: string, promptTitle?: string, prompt?: string, formula1?: string, formula2?: string, };
