// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefinedNamePatch = {
  name: string;
  formula: string;
  scope?: string;
  comment?: string;
  hidden?: boolean;
};
