// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefinedNameInfo = { name: string, reference: string, scope?: string, comment?: string, hidden: boolean, };
