// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyReference } from "./DependencyReference.js";

export type DependencyInfo = {
  sheet: string;
  reference: string;
  row: number;
  column: number;
  precedents: Array<DependencyReference>;
  dependents: Array<DependencyReference>;
};
