// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuiltInUnit } from "./BuiltInUnit.js";

/**
 * Value-axis display units (`c:dispUnits`), distilled from ooxmlsdk `DisplayUnits`.
 *
 * Either a {@link BuiltInUnit} name (`"millions"`) or a custom divisor number
 * (`1000000`). Both scale the axis tick labels; built-in units also render their
 * name as a label band. Intentionally not modeled (preserved on update, author
 * via raw XML): a custom `dispUnitsLbl` text/styling and `extLst`.
 */
export type DisplayUnits = BuiltInUnit | number;
