// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How blank/empty source cells are plotted (`c:dispBlanksAs`, OOXML
 * `ST_DispBlanksAs`). `Gap` leaves a hole, `Zero` plots zero, `Span` bridges
 * across the gap (line/area charts). Excel defaults new charts to `Gap`.
 */
export type DispBlanksAs = "span" | "gap" | "zero";
