// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnderlinePatch } from "./UnderlinePatch.js";

export type FontPatch = { name?: string, size?: number, bold?: boolean, italic?: boolean, underline?: UnderlinePatch, strike?: boolean, color?: string, };
