// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GradientStopPatch } from "./GradientStopPatch.js";
import type { GradientType } from "./GradientType.js";

export type GradientFillPatch = { kind?: GradientType, degree?: number, left?: number, right?: number, top?: number, bottom?: number, stops: Array<GradientStopPatch>, };
