// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeaderFooterInfo = { differentOddEven?: boolean, differentFirst?: boolean, scaleWithDoc?: boolean, alignWithMargins?: boolean, oddHeader?: string, oddFooter?: string, evenHeader?: string, evenFooter?: string, firstHeader?: string, firstFooter?: string, };
