// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HyperlinkPatch = { target?: string, location?: string, tooltip?: string, display?: string, };
