// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfIconSetKind } from "./CfIconSetKind.js";
import type { CfValueObject } from "./CfValueObject.js";

export type IconSetPatch = {
  iconSet: CfIconSetKind;
  values: Array<CfValueObject>;
  showValue?: boolean;
  percent?: boolean;
  reverse?: boolean;
};
