// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSpec } from "./AnchorSpec.js";

export type ImageUpdate = {
  name?: string;
  anchor?: AnchorSpec;
  rotationDegrees?: number;
  flipHorizontal?: boolean;
  flipVertical?: boolean;
};
