// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";
import type { ImageFormat } from "./ImageFormat.js";

export type ImagePatch = {
  sheet: string;
  name?: string;
  anchor: ChartAnchor;
  bytes: Uint8Array | number[];
  format?: ImageFormat;
  rotationDegrees?: number;
  cropLeftPct?: number;
  cropTopPct?: number;
  cropRightPct?: number;
  cropBottomPct?: number;
  flipHorizontal?: boolean;
  flipVertical?: boolean;
};
