// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preset line dash pattern (`a:prstDash/@val`, OOXML `ST_PresetLineDashVal`),
 * transliterated from ooxmlsdk `PresetLineDashValues`.
 */
export type LineDash = "solid" | "dot" | "dash" | "lgDash" | "dashDot" | "lgDashDot" | "lgDashDotDot" | "sysDash" | "sysDot" | "sysDashDot" | "sysDashDotDot";
