// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data-point marker symbol (`c:marker/c:symbol`, OOXML `ST_MarkerStyle`).
 * Applies to line and scatter series; ignored for other chart kinds.
 */
export type MarkerStyle = "auto" | "circle" | "dash" | "diamond" | "dot" | "none" | "picture" | "plus" | "square" | "star" | "triangle" | "x";
