// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeInfo = {
  sheet: string;
  reference: string;
  startRow: number;
  startColumn: number;
  endRow: number;
  endColumn: number;
  rows: number;
  columns: number;
};
