// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StylePatch } from "./StylePatch.js";

/**
 * A workbook-scoped named cell style (a cellStyles entry + its master xf in
 * cellStyleXfs). `style` is the formatting baked into the master xf; apply it
 * to cells with `StylePatch.namedStyle`.
 *
 * schema-excluded: outline_level, hidden, custom_builtin, extLst, xml_other_attrs
 */
export type NamedStylePatch = { name: string; style: StylePatch; builtinId?: number };
