// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PageMarginsInfo = {
  left: number;
  right: number;
  top: number;
  bottom: number;
  header: number;
  footer: number;
};
