// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PivotGridCell } from "./PivotGridCell.js";

export type PivotGrid = { rows: number, cols: number, cells: Array<PivotGridCell>, };
