// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PivotDataField } from "./PivotDataField.js";
import type { PivotFieldFilter } from "./PivotFieldFilter.js";

export type PivotInfo = {
  sheet: string;
  id: string;
  name: string;
  locationRef: string;
  anchorCell: string;
  sourceRef: string;
  rowFields: Array<string>;
  columnFields: Array<string>;
  filterFields: Array<string>;
  dataFields: Array<PivotDataField>;
  hiddenItems?: Array<PivotFieldFilter>;
};
