// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PivotAggregation } from "./PivotAggregation.js";

export type PivotDataField = { field: string, aggregation: PivotAggregation, name?: string, numberFormat?: string, };
