// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PivotAggregation = "sum" | "count" | "average" | "max" | "min" | "product" | "count_nums" | "std_dev" | "std_devp" | "var" | "varp";
