// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PivotCellRole } from "./PivotCellRole.js";

export type PivotGridCell = { row: number, col: number, role: PivotCellRole, kind: string, value?: string, };
