// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Radar plot style (`c:radarStyle`, OOXML `ST_RadarStyle`). Radar charts only.
 *
 * `Standard` draws connecting lines only, `Marker` adds point markers, `Filled`
 * fills each series' polygon. Defaults to `Standard` when omitted.
 */
export type RadarStyle = "standard" | "marker" | "filled";
