// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCellValue } from "./ApiCellValue.js";

export type RangeInfo = {
  sheet: string;
  reference: string;
  startRow: number;
  startColumn: number;
  endRow: number;
  endColumn: number;
  rows: number;
  columns: number;
  values: Array<Array<ApiCellValue>>;
  formulas: Array<Array<string | null>>;
};
