// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineCellValue } from "./EngineCellValue.js";
import type { FormulaFallback } from "./FormulaFallback.js";

export type RecalcCell = {
  r: number;
  c: number;
  formula: string;
  cachedValue?: EngineCellValue;
  value: EngineCellValue;
  fallback?: FormulaFallback;
};
