// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecalcCell } from "./RecalcCell.js";

export type RecalcSheet = { index: number, name: string, cells: Array<RecalcCell>, };
