// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichTextRun } from "./RichTextRun.js";

/**
 * A rich-text cell value: an ordered list of formatted runs (`CT_Rst`).
 *
 * schema-excluded: t, rPh, phoneticPr
 */
export type RichText = { runs: Array<RichTextRun>, };
