// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontPatch } from "./FontPatch.js";

/**
 * A single formatted run of a rich-text cell (`CT_RElt`). `text` is the run's
 * literal text; `font` carries its per-run formatting (`CT_RPrElt`).
 */
export type RichTextRun = { text: string; font?: FontPatch };
