// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCellValue } from "./ApiCellValue.js";
import type { SearchHit } from "./SearchHit.js";

export type SearchMatch = {
  sheet: string;
  reference: string;
  row: number;
  column: number;
  hit: SearchHit;
  matched: string;
  value: ApiCellValue;
  formula?: string;
};
