// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMode } from "./SearchMode.js";
import type { SearchTarget } from "./SearchTarget.js";

export type SearchOptions = { sheet?: string, range?: string, target: SearchTarget, mode: SearchMode, caseSensitive: boolean, maxResults?: number, includeHidden?: boolean, };
