// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";
import type { ShapeLineEnd } from "./ShapeLineEnd.js";

export type ShapePatch = {
  sheet: string;
  name?: string;
  anchor: ChartAnchor;
  preset: string;
  fillColor?: string;
  lineColor?: string;
  lineWidthEmu?: bigint;
  text?: string;
  textColor?: string;
  fontSizePt?: number;
  bold?: boolean;
  italic?: boolean;
  rotationDegrees?: number;
  flipHorizontal?: boolean;
  flipVertical?: boolean;
  align?: string;
  verticalAlign?: string;
  underline?: boolean;
  headEnd?: ShapeLineEnd;
  tailEnd?: ShapeLineEnd;
};
