// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSpec } from "./AnchorSpec.js";
import type { ShapeLineEnd } from "./ShapeLineEnd.js";

export type ShapePatch = { name?: string, anchor: AnchorSpec, preset: string, fillColor?: string, lineColor?: string, lineWidthEmu?: bigint, text?: string, textColor?: string, fontSizePt?: number, bold?: boolean, italic?: boolean, rotationDegrees?: number, flipHorizontal?: boolean, flipVertical?: boolean, align?: string, verticalAlign?: string, underline?: boolean, headEnd?: ShapeLineEnd, tailEnd?: ShapeLineEnd, };
