// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartAnchor } from "./ChartAnchor.js";

export type ShapeInfo = {
  sheet: string;
  id: string;
  name: string;
  anchor: ChartAnchor;
  preset: string;
  fillColor?: string;
  lineColor?: string;
  text?: string;
  rotationDegrees: number;
  flipHorizontal: boolean;
  flipVertical: boolean;
};
