// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderFooterInfo } from "./HeaderFooterInfo.js";
import type { PageMarginsInfo } from "./PageMarginsInfo.js";
import type { PageSetupSettings } from "./PageSetupSettings.js";
import type { PrintOptionsInfo } from "./PrintOptionsInfo.js";

export type SheetPageSetup = {
  sheet: string;
  page?: PageSetupSettings;
  margins?: PageMarginsInfo;
  printOptions?: PrintOptionsInfo;
  headerFooter?: HeaderFooterInfo;
  printArea?: string;
  printTitleRows?: string;
  printTitleColumns?: string;
  rowBreaks: Array<number>;
  columnBreaks: Array<number>;
};
