// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderFooterInfo } from "./HeaderFooterInfo.js";
import type { PageMarginsPatch } from "./PageMarginsPatch.js";
import type { PageSetupSettings } from "./PageSetupSettings.js";
import type { PrintOptionsInfo } from "./PrintOptionsInfo.js";

export type SheetPageSetupPatch = { page?: PageSetupSettings, margins?: PageMarginsPatch, printOptions?: PrintOptionsInfo, headerFooter?: HeaderFooterInfo, };
