// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SheetInfo = { index: number, id: number, name: string, state?: "hidden" | "veryHidden", rowCount: number, columnCount: number, active: boolean, };
