// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SheetPropertiesPatch = { tabColor?: string, zoom?: number, showZeros?: boolean, rightToLeft?: boolean, defaultRowHeight?: number, defaultColWidth?: number, };
