// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SparklineAxisType } from "./SparklineAxisType.js";
import type { SparklineDisplayBlanks } from "./SparklineDisplayBlanks.js";
import type { SparklineEntry } from "./SparklineEntry.js";
import type { SparklineKind } from "./SparklineKind.js";

export type SparklineGroupInfo = { sheet: string, id: string, kind: SparklineKind, sparklines: Array<SparklineEntry>, markers?: boolean, high?: boolean, low?: boolean, first?: boolean, last?: boolean, negative?: boolean, displayXAxis?: boolean, rightToLeft?: boolean, displayEmptyCellsAs?: SparklineDisplayBlanks, minAxisType?: SparklineAxisType, maxAxisType?: SparklineAxisType, manualMin?: number, manualMax?: number, lineWeight?: number, seriesColor?: string, negativeColor?: string, axisColor?: string, markersColor?: string, firstColor?: string, lastColor?: string, highColor?: string, lowColor?: string, };
