// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignmentPatch } from "./AlignmentPatch.js";
import type { BorderPatch } from "./BorderPatch.js";
import type { FillPatch } from "./FillPatch.js";
import type { FontPatch } from "./FontPatch.js";
import type { ProtectionPatch } from "./ProtectionPatch.js";

export type StylePatch = { font?: FontPatch, fill?: FillPatch, border?: BorderPatch, alignment?: AlignmentPatch, numberFormat?: string, protection?: ProtectionPatch, namedStyle?: string, };
