// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableColumnPatch } from "./TableColumnPatch.js";
import type { TableStylePatch } from "./TableStylePatch.js";

export type TablePatch = { name: string, displayName?: string, reference?: string, headerRowCount?: number, totalsRowCount?: number, hasAutoFilter?: boolean, columns?: Array<TableColumnPatch>, style?: TableStylePatch, };
