// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableTotalsFunction = "none" | "sum" | "average" | "count" | "countNums" | "min" | "max" | "stdDev" | "var" | "custom";
