// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableTotalsFunction } from "./TableTotalsFunction.js";

export type TableColumnPatch = { name?: string, totalsFunction?: TableTotalsFunction, totalsLabel?: string, totalsFormula?: string, calculatedColumnFormula?: string, };
