// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadedNoteInfo = { sheet: string, reference: string, row: number, column: number, id: string, parentId?: string, personId: string, author: string, text: string, date?: string, done: boolean, };
