// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis tick-mark style (`c:majorTickMark`/`c:minorTickMark`, OOXML `ST_TickMark`).
 */
export type TickMark = "cross" | "inside" | "outside" | "none";
