// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tick-label placement (`c:tickLblPos`, OOXML `ST_TickLblPos`).
 */
export type TickLabelPosition = "high" | "low" | "nextTo" | "none";
