// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trendline regression type (`c:trendlineType/@val`, OOXML `ST_TrendlineType`),
 * transliterated from ooxmlsdk `TrendlineValues`.
 */
export type TrendlineKind = "exp" | "linear" | "log" | "movingAvg" | "poly" | "power";
