// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkbookProtectionInfo = { lockStructure?: boolean, lockWindows?: boolean, lockRevision?: boolean, workbookPassword?: string, workbookAlgorithmName?: string, workbookHashValue?: string, workbookSaltValue?: string, workbookSpinCount?: number, revisionsPassword?: string, revisionsAlgorithmName?: string, revisionsHashValue?: string, revisionsSaltValue?: string, revisionsSpinCount?: number, };
