// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkbookPropertiesPatch = {
  title?: string;
  subject?: string;
  creator?: string;
  keywords?: string;
  description?: string;
  lastModifiedBy?: string;
  category?: string;
  contentStatus?: string;
  identifier?: string;
  language?: string;
  revision?: string;
  version?: string;
  created?: string;
  modified?: string;
  lastPrinted?: string;
};
