// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderLine } from "./BorderLine.js";

export type Border = {
  left?: BorderLine;
  right?: BorderLine;
  top?: BorderLine;
  bottom?: BorderLine;
  diagonalUp: boolean;
  diagonalDown: boolean;
  diagonal?: BorderLine;
};
