// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRun } from "./TextRun.js";

export type Cell = {
  r: number;
  c: number;
  type: string;
  value?: string;
  formula?: string;
  styleIndex?: number;
  runs: Array<TextRun>;
};
