// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 1-based cell address. Used by `Pivot.filter_arrow_cells`.
 */
export type CellRef = { r: number; c: number };
