// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfColorScaleStop } from "./CfColorScaleStop.js";

export type CfColorScale = { stops: Array<CfColorScaleStop> };
