// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfvoStop } from "./CfvoStop.js";
import type { Color } from "./Color.js";

export type CfDataBar = {
  min: CfvoStop;
  max: CfvoStop;
  color: Color;
  negativeColor?: Color;
  minLengthPct: number;
  maxLengthPct: number;
  showValue: boolean;
  gradient: boolean;
};
