// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfvoStop } from "./CfvoStop.js";

export type CfIconSet = {
  iconSet: string;
  cfvos: Array<CfvoStop>;
  showValue: boolean;
  reverse: boolean;
};
