// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfColorScale } from "./CfColorScale.js";
import type { CfDataBar } from "./CfDataBar.js";
import type { CfIconSet } from "./CfIconSet.js";

export type CfRule = {
  priority: number;
  kind: string;
  colorScale?: CfColorScale;
  dataBar?: CfDataBar;
  iconSet?: CfIconSet;
  operator?: string;
  operands: Array<string>;
  dxfId?: number;
  stopIfTrue: boolean;
  rank?: number;
  bottom: boolean;
  percent: boolean;
  aboveAverage?: boolean;
  equalAverage: boolean;
  stdDev?: number;
  text?: string;
  timePeriod?: string;
};
