// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartView3D = {
  rotX?: number;
  rotY?: number;
  perspective?: number;
  rightAngleAxes?: boolean;
  depthPercent?: number;
  heightPercent?: number;
};
