// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartTrendline = {
  type: string;
  polynomialOrder?: number;
  period?: number;
  intercept?: number;
  forward?: number;
  backward?: number;
  color?: string;
  lineWidthEmu?: number;
  lineDash?: string;
};
