// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartFillGradientStop } from "./ChartFillGradientStop.js";

export type ChartPointFill = {
  index: number;
  kind: string;
  gradientStops: Array<ChartFillGradientStop>;
  gradientAngle?: number;
  patternPreset?: string;
  patternForeground?: string;
  patternBackground?: string;
};
