// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataLabels } from "./DataLabels.js";

export type ChartSeries = {
  name: string;
  nameRef?: string;
  color?: string;
  values: Array<number>;
  valuesRef?: string;
  xValues: Array<number>;
  xValuesRef?: string;
  bubbleSizes: Array<number>;
  bubbleSizesRef?: string;
  pointColors: Array<string>;
  dataLabels?: DataLabels;
  axisGroup?: string;
  chartType?: string;
  markerSymbol?: string;
  lineWidthEmu?: number;
  lineDash?: string;
};
