// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartDataTable = {
  showHorzBorder: boolean;
  showVertBorder: boolean;
  showOutline: boolean;
  showKeys: boolean;
};
