// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartErrorBars = {
  errDir: string;
  errBarType: string;
  errValType: string;
  value?: number;
  noEndCap?: boolean;
  plusValues: Array<number>;
  minusValues: Array<number>;
  color?: string;
  lineWidthEmu?: number;
  lineDash?: string;
};
