// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartSeries } from "./ChartSeries.js";
import type { DataLabels } from "./DataLabels.js";

export type Chart = {
  /**
   * `column`, `bar`, `line`, `pie`, `area`, `scatter`, `unknown`.
   * `column` and `bar` collapse into one `BarChart` schema entry; the
   * barDir attribute distinguishes them.
   */
  type: string;
  title?: string;
  series: Array<ChartSeries>;
  /**
   * X-axis labels (categories). Often pulled from the cat strRef cache;
   * if absent the renderer falls back to series-relative indices.
   */
  categories: Array<string>;
  /**
   * Formula reference (e.g. `Sheet1!$B$1:$E$1`) used to populate
   * `categories` from live workbook data when the chart's strCache is
   * empty. Resolution happens after sheets are extracted.
   */
  categoriesRef?: string;
  /**
   * `t`, `b`, `l`, `r`, `tr` (ECMA-376 legend positions).
   */
  legendPos?: string;
  /**
   * Number-format for the value axis (e.g. "$#,##0").
   */
  valueFormat?: string;
  /**
   * Number-format string for category-axis labels. When omitted, labels
   * are rendered as plain text.
   */
  categoriesFormat?: string;
  /**
   * `clustered`, `stacked`, `percentStacked`, `standard` (line/area).
   */
  grouping?: string;
  /**
   * `col` or `bar` (only meaningful for chart_type == bar).
   */
  barDir?: string;
  /**
   * Scatter style: `line`, `lineMarker`, `marker`, `smooth`,
   * `smoothMarker`. Only meaningful for chart_type == scatter.
   * When `None`, the renderer treats the chart as marker-only
   * (matches Excel's UI default even though the OOXML enum
   * default is `line`).
   */
  scatterStyle?: string;
  /**
   * Radar style: `standard`, `marker`, `filled`. Only meaningful for
   * chart_type == radar. ECMA-376 §21.2.2.176; defaults to
   * `standard` (line, no markers) per the schema, though Excel's UI
   * default for new radar charts is `marker`.
   */
  radarStyle?: string;
  /**
   * Chart-level `<c:dLbls>` — the per-chart-group default. Series-
   * level `dataLabels` overrides on a per-series basis. None ⇒ no
   * labels (Excel's default for every chart type).
   */
  dataLabels?: DataLabels;
  secondaryAxis: boolean;
  valueFormatSecondary?: string;
  valueMin?: number;
  valueMax?: number;
  valueMinSecondary?: number;
  valueMaxSecondary?: number;
  /**
   * `<c:majorUnit val="N"/>` on the primary value axis — the explicit
   * tick step. When present, the renderer generates ticks at
   * `min + k*majorUnit` instead of using its niceTicks heuristic, so
   * axis labels match Excel's authored cadence (e.g. NWC line chart
   * authored `<c:majorUnit val="9000"/>` with `<c:max val="45000"/>`
   * produces 0/9/18/27/36/45 once `dispUnits=1000` scales tick labels).
   * Stored in source units (before any `dispUnits` divisor).
   */
  majorUnit?: number;
  /**
   * Same as `major_unit`, but for the secondary value axis.
   */
  majorUnitSecondary?: number;
  barGapWidth?: number;
  barOverlap?: number;
  xAxisTitle?: string;
  yAxisTitle?: string;
  yAxisTitleSecondary?: string;
  showMajorGridlines?: boolean;
  showMajorGridlinesSecondary?: boolean;
  dispUnits?: number;
  dispUnitsLabel?: string;
  dispUnitsSecondary?: number;
  dispUnitsLabelSecondary?: string;
  bubbleScale?: number;
  sizeRepresents?: string;
  /**
   * Stock-chart decoration toggles (ECMA-376 §21.2.2.207).
   * `hiLowLines` connect each category's high+low values with a
   * vertical line; xlsxwriter emits `<c:hiLowLines/>` by default
   * for HLC/OHLC stock. `upDownBars` paint a column between
   * open and close (white-fill for up days, black-fill for down)
   * — only meaningful when series count >= 4 (OHLC). `dropLines`
   * connect each value point down to the category axis; rarely
   * authored on stock charts but legal.
   */
  stockHiLowLines: boolean;
  stockUpDownBars: boolean;
  stockDropLines: boolean;
  /**
   * chartEx (`cx:`) series layout id: `waterfall`, `funnel`,
   * `treemap`, `sunburst`, `boxWhisker`, `paretoLine`, `regionMap`,
   * `clusteredColumn` (histogram). When set, `chart_type` is
   * `chartex` and the renderer dispatches on this field. Today
   * only `waterfall` is rendered; others fall back to the placeholder
   * chart box.
   */
  cxLayout?: string;
  /**
   * Per-point subtotal flags for `cx_layout == "waterfall"` (and
   * future pareto/histogram variants). 0-based category indices
   * flagged as subtotal/total bars — the renderer paints them
   * from the floor (not stacked on the previous cumulative).
   */
  cxSubtotalIndices: Array<number>;
  /**
   * Waterfall fill colors: `[increment, decrement, subtotal]`.
   * Each entry is a CSS color string, or empty when authored
   * `<cx:layoutPr><cx:{increment,decrement,subtotal}>` is absent
   * — in which case the renderer uses Office defaults (green /
   * red / blue).
   */
  cxWaterfallIncrementColor?: string;
  cxWaterfallDecrementColor?: string;
  cxWaterfallSubtotalColor?: string;
};
