// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Col = {
  min: number;
  max: number;
  widthPx: number;
  styleIndex?: number;
  hidden: boolean;
  outlineLevel: number;
};
