// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColumnarCells = {
  count: number;
  r: string;
  c: string;
  kind: string;
  valueIdx: string;
  formulaIdx: string;
  styleIdx: string;
  runsIdx: string;
  rowPtr: string;
};
