// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfRule } from "./CfRule.js";
import type { Merge } from "./Merge.js";

export type ConditionalFormat = { ranges: Array<Merge>; rules: Array<CfRule> };
