// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `<tableStyle name="…">` entry from `xl/styles.xml`'s
 * `<tableStyles>` block. Each style is a bag of
 * `<tableStyleElement type="…" dxfId="N"/>` references; the renderer
 * uses the dxf at index N as an overlay for that band of the table
 * (header row, first/second row stripe, total row, etc.).
 *
 * We surface the elements we actually paint today. Bands we don't
 * implement (column stripes, subtotal rows, page-field cells) are
 * dropped on the floor — add fields as the renderer learns more
 * bands. ECMA-376 §18.8.40 has the full enumeration.
 */
export type CustomTableStyle = {
  name: string;
  /**
   * `dxfId` for the whole-table overlay (border defaults, base fill).
   */
  wholeTable?: number;
  /**
   * `dxfId` for the header row band (fill + bold/colored font).
   */
  headerRow?: number;
  /**
   * `dxfId` for the totals row band.
   */
  totalRow?: number;
  /**
   * `dxfId` for the first row stripe (the tint applied to alternating
   * data rows; in Excel's Medium styles this is the accent-tinted band).
   */
  firstRowStripe?: number;
  /**
   * `dxfId` for the second row stripe (the *other* alternating band;
   * usually unset — implied as the default "no fill" complement).
   */
  secondRowStripe?: number;
  /**
   * `dxfId` for the first column band (typically bold).
   */
  firstColumn?: number;
  /**
   * `dxfId` for the last column band (typically bold).
   */
  lastColumn?: number;
};
