// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomTableStyle = {
  name: string;
  wholeTable?: number;
  headerRow?: number;
  totalRow?: number;
  firstRowStripe?: number;
  secondRowStripe?: number;
  firstColumn?: number;
  lastColumn?: number;
};
