// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointDataLabel } from "./PointDataLabel.js";

export type DataLabels = {
  showValue: boolean;
  showCategory: boolean;
  showSeriesName: boolean;
  showPercent: boolean;
  position?: string;
  separator?: string;
  numFmt?: string;
  pointOverrides: Array<PointDataLabel>;
};
