// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointDataLabel } from "./PointDataLabel.js";

/**
 * `<c:dLbls>` — what to print next to each data point. Mirrors the
 * OOXML `CT_DLbls` block. Rendered text per point is built by joining
 * the enabled fields with `separator` (default `", "`):
 *
 *   `[seriesName][sep][category][sep][value | percent]`
 *
 * Empty when extracted from `<c:delete val="1"/>` (suppression marker).
 */
export type DataLabels = {
  showValue: boolean;
  showCategory: boolean;
  showSeriesName: boolean;
  /**
   * Show value as % of category total. Pie/doughnut natively in
   * Excel; we honor it on any chart type that has a category total.
   */
  showPercent: boolean;
  /**
   * `ctr`, `inEnd`, `inBase`, `outEnd`, `t`, `b`, `l`, `r`, `bestFit`.
   * None ⇒ chart-type default (`outEnd` for column, `r` for bar,
   * `ctr` for line/scatter, `outEnd`/`bestFit` for pie).
   */
  position?: string;
  /**
   * String inserted between fields when more than one show* is on.
   * Default `", "`.
   */
  separator?: string;
  /**
   * Number-format code for the value field, e.g. `"0.0%"`. None
   * falls back to the chart's `valueFormat`.
   */
  numFmt?: string;
  /**
   * Per-data-point `<c:dLbl idx=N>` overrides. Each entry replaces
   * the base block on just one data point: either suppresses that
   * point's label (`<c:delete val="1"/>`), substitutes literal
   * text (`<c:tx>`), or tweaks position / show* / numFmt for just
   * that point. Common authoring idioms: pies that label only the
   * largest slice, column charts that highlight an outlier, line
   * charts that name only the endpoints. Empty Vec when the source
   * has no `<c:dLbl>` children.
   */
  pointOverrides: Array<PointDataLabel>;
};
