// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefinedName = {
  name: string;
  /**
   * Target formula / reference text, e.g. `'Sheet 1'!$A$1`.
   */
  formula: string;
  /**
   * Zero-based sheet index for sheet-scoped names. Omitted for workbook
   * scope.
   */
  localSheetId?: number;
};
