// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chart } from "./Chart.js";
import type { DrawingAnchor } from "./DrawingAnchor.js";
import type { Image } from "./Image.js";
import type { Shape } from "./Shape.js";

/**
 * One drawing object placed on the sheet, with its xlsx cell-anchor.
 */
export type Drawing = {
  /**
   * `chart`, `image`, `shape` (only `chart` and `image` are rendered).
   */
  kind: string;
  anchor: DrawingAnchor;
  chart?: Chart;
  image?: Image;
  /**
   * Vector shape tree (`<xdr:sp>` / `<xdr:grpSp>`). Only set when
   * `kind == "shape"`. A drawing anchor wraps a tree of shape nodes
   * (one per `<xdr:sp>`) whose positions are stored relative to the
   * anchor bbox (0..1). Nested groups are flattened — the extractor
   * applies each `<xdr:grpSp>`'s `xfrm/chOff/chExt` mapping during
   * the walk so the renderer only ever sees leaf `<xdr:sp>` nodes.
   * See ECMA-376 §20.5.2 (SpreadsheetML drawing shapes) and
   * §20.1.7.5 (xfrm) for the group-transform semantics.
   */
  shape?: Shape;
};
