// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * twoCellAnchor: from/to cell indices (0-based) + EMU offsets within the cell.
 * 1 EMU = 1/9525 px at 96 DPI.
 */
export type DrawingAnchor = {
  fromCol: number;
  fromColOffEmu: number;
  fromRow: number;
  fromRowOffEmu: number;
  toCol: number;
  toColOffEmu: number;
  toRow: number;
  toRowOffEmu: number;
  /**
   * `oneCellAnchor` width in EMU. When set, the renderer uses this value
   * instead of the approximated `to` cell.
   */
  extEmuCx?: number | null;
  /**
   * `oneCellAnchor` height in EMU. See `extEmuCx`.
   */
  extEmuCy?: number | null;
};
