// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrawingAnchor = {
  anchorKind?: string;
  editAs?: string;
  fromCol: number;
  fromColOffEmu: number;
  fromRow: number;
  fromRowOffEmu: number;
  toCol: number;
  toColOffEmu: number;
  toRow: number;
  toRowOffEmu: number;
  extEmuCx?: number | null;
  extEmuCy?: number | null;
};
