// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Merge } from "./Merge.js";

export type Hyperlink = {
  range: Merge;
  target?: string;
  location?: string;
  tooltip?: string;
  display?: string;
};
