// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inline-encoded raster image extracted from `xl/media/*`.
 */
export type Image = {
  /**
   * `data:image/png;base64,...` style URI, ready to feed to <img>.
   */
  dataUri: string;
};
