// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `<a:headEnd>` / `<a:tailEnd>` arrowhead descriptor.
 */
export type LineEnd = {
  /**
   * `type="..."`: `none`/`triangle`/`stealth`/`diamond`/`oval`/`arrow`.
   * `None` ⇒ `none`.
   */
  kind?: string;
  /**
   * `w="sm|med|lg"`. `None` ⇒ `med`.
   */
  w?: string;
  /**
   * `len="sm|med|lg"`. `None` ⇒ `med`.
   */
  len?: string;
};
