// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellRef } from "./CellRef.js";
import type { Merge } from "./Merge.js";

export type Pivot = { name: string; range: Merge; filterArrowCells: Array<CellRef> };
