// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PivotFilterAxis } from "./PivotFilterAxis.js";

export type PivotFilterArrow = { r: number; c: number; field: string; axis: PivotFilterAxis };
