// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Merge } from "./Merge.js";
import type { PivotFilterArrow } from "./PivotFilterArrow.js";

export type Pivot = { name: string; range: Merge; filterArrowCells: Array<PivotFilterArrow> };
