// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PointDataLabel = {
  idx: number;
  delete: boolean;
  text?: string;
  position?: string;
  numFmt?: string;
  showValue?: boolean;
  showCategory?: boolean;
  showSeriesName?: boolean;
  showPercent?: boolean;
};
