// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Override block for one data point inside a `<c:dLbls>` parent. All
 * override fields are `Option`/`bool` so unset values inherit from
 * the parent `DataLabels`.
 */
export type PointDataLabel = {
  /**
   * 0-based index of the data point within the series.
   */
  idx: number;
  /**
   * `<c:dLbl><c:delete val="1"/></c:dLbl>` — suppress this point's
   * label entirely. When true, every other field is ignored.
   */
  delete: boolean;
  /**
   * Literal text override from `<c:tx>` (rich-text runs flattened).
   * When set, the renderer prints this string verbatim instead of
   * computing `value`/`category`/`percent` from the source data.
   */
  text?: string;
  /**
   * Override `<c:dLblPos>`; same enum values as `DataLabels.position`.
   */
  position?: string;
  /**
   * Override `<c:numFmt>` format code.
   */
  numFmt?: string;
  /**
   * Per-point show* overrides. `None` ⇒ inherit parent.
   */
  showValue?: boolean;
  showCategory?: boolean;
  showSeriesName?: boolean;
  showPercent?: boolean;
};
