// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell.js";

export type Row = {
  index: number;
  heightPx?: number;
  cells: Array<Cell>;
  styleIndex?: number;
  hidden: boolean;
  outlineLevel: number;
};
