// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShapeBlipFill = {
  /**
   * Data URI for the embedded image. When an `asvg:svgBlip` sidecar
   * is present the SVG version is preferred (vector → crisper at
   * scale); otherwise this is the raster fallback resolved from
   * `<a:blip r:embed>`.
   */
  dataUri: string;
  /**
   * Source-rectangle crop in 1/100000 units `[left, top, right, bottom]`,
   * matching `<a:srcRect>` semantics. Omitted when absent or all-zero.
   */
  srcRect?: Array<number>;
  /**
   * `stretch` (default) or `tile`. Tile geometry beyond `kind` is not
   * yet modeled — v0 paints `tile` as stretch.
   */
  kind?: string;
};
