// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeNode } from "./ShapeNode.js";

/**
 * `<xdr:sp>` autoshape (rectangles, callouts, banners, sticky notes,
 * arrows). v0 paints fill + outline + centered text. Unknown presets
 * fall back to a plain rectangle — Excel's chrome-shape vocabulary is
 * vast (~200 presets) and most workbook chrome is rounded-rect or
 * arrow; we'll grow this as fixtures demand.
 */
export type Shape = {
  /**
   * Leaf shapes in z-order (first painted first; later ones overlay).
   * Groups are flattened — children inherit the accumulated transform.
   */
  nodes: Array<ShapeNode>;
};
