// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeGradientStop } from "./ShapeGradientStop.js";

export type ShapeGradient = {
  stops: Array<ShapeGradientStop>;
  kind: string;
  angleDeg?: number;
  path?: string;
  fillToRect?: Array<number>;
};
