// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRun } from "./TextRun.js";

export type ShapeParagraph = { align?: string; runs: Array<TextRun> };
