// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineEnd } from "./LineEnd.js";
import type { ShapeParagraph } from "./ShapeParagraph.js";

/**
 * One leaf `<xdr:sp>` (or `<xdr:cxnSp>`) positioned inside the drawing
 * anchor's bbox via fractional coordinates (0..1). The renderer maps
 * these to the anchor's resolved pixel rect.
 */
export type ShapeNode = {
  /**
   * Fractional bbox inside the drawing-anchor's resolved pixel rect.
   */
  relX: number;
  relY: number;
  relW: number;
  relH: number;
  /**
   * `<a:prstGeom prst="..."/>` token (`rect`, `roundRect`, `ellipse`,
   * `leftArrow`, …). None ⇒ no preset (custom geometry); renderer
   * falls back to a plain rectangle.
   */
  preset?: string;
  /**
   * Resolved `#RRGGBB` fill color from `<a:solidFill>`. `None` when
   * `<a:noFill/>` is authored or no fill is present.
   */
  fill?: string;
  /**
   * Resolved `#RRGGBB` outline color. `None` when `<a:noFill/>` or
   * `<a:ln>` is absent.
   */
  outlineColor?: string;
  /**
   * Outline stroke width in EMU. `None` ⇒ Excel default (~9525 EMU
   * = 1pt). 0 ⇒ hairline.
   */
  outlineWidthEmu?: number;
  /**
   * `<a:bodyPr anchor="..."/>` vertical anchor (`t`/`ctr`/`b`).
   * Default `t` (top).
   */
  textAnchor?: string;
  /**
   * Rotation in 1/60000 degree units (OOXML's `rot` attr unit).
   * `None` ⇒ 0.
   */
  rotation?: number;
  /**
   * Text paragraphs.
   */
  paragraphs: Array<ShapeParagraph>;
  /**
   * `<a:bodyPr wrap="..."/>` token (`square` ⇒ wrap on word
   * boundaries; `none` ⇒ no wrap). Default `square` (Excel's
   * implicit default when the attr is absent).
   */
  textWrap?: string;
  /**
   * `<a:bodyPr lIns/tIns/rIns/bIns/>` text-body insets in EMU.
   * Length-4 `[left, top, right, bottom]`. `None` ⇒ use the
   * DrawingML defaults (lIns/rIns = 91440 EMU ≈ 0.1", tIns/bIns
   * = 45720 EMU ≈ 0.05" — ECMA-376 §21.1.2.1.1). Cells with one
   * or more inset attrs present surface all four (missing slots
   * fall back to the per-edge default), so the renderer never
   * has to mix-and-match.
   */
  textInsetsEmu?: Array<number>;
  /**
   * Inline picture node — when this is `Some(...)`, the node
   * renders an embedded raster image (`<xdr:pic>` nested inside
   * `<xdr:grpSp>`) instead of a `prstGeom` rect. The string is a
   * `data:<mime>;base64,...` URI (same encoding the top-level
   * `Image.dataUri` uses, sharing the renderer image cache).
   * Fill / outline / paragraphs are ignored when this is set.
   */
  imageDataUri?: string;
  /**
   * `<a:srcRect l="" t="" r="" b=""/>` crop, in 1/1000 percent of
   * the source image dimensions. Length-4 vec: [left, top, right,
   * bottom]. Renderer uses these as fractional crop insets when
   * painting `image_data_uri`.
   */
  imageSrcRect?: Array<number>;
  /**
   * `<a:xfrm flipH="1"/>` — horizontal flip of the shape bbox.
   * Connectors lean on this heavily to express direction (a
   * `straightConnector1` with flipH goes top-right → bottom-left
   * instead of top-left → bottom-right).
   */
  flipH?: boolean;
  /**
   * `<a:xfrm flipV="1"/>` — vertical flip.
   */
  flipV?: boolean;
  /**
   * `<a:prstDash val="..."/>` token (`solid`/`dash`/`dot`/`dashDot`/
   * `lgDash`/`sysDash`/...). `None` ⇒ solid. Renderer translates to
   * a canvas dash pattern scaled by stroke width.
   */
  lineDash?: string;
  /**
   * Whether this node is a `<xdr:cxnSp>` connector. When `Some(true)`
   * the renderer paints a stroked path (no fill, no text) along the
   * node's diagonal / Z-route depending on `preset`. Same shape
   * vocabulary is reused for non-connector `<xdr:sp>` line presets
   * (`line`, `lineInv`) by setting this flag at extraction time.
   */
  isConnector?: boolean;
  /**
   * `<a:headEnd>` arrowhead at the connector's start point.
   */
  headEnd?: LineEnd;
  /**
   * `<a:tailEnd>` arrowhead at the connector's end point.
   */
  tailEnd?: LineEnd;
  /**
   * `<a:avLst><a:gd name="adj1" fmla="val NNNNN"/></a:avLst>` first
   * adjustment value, in DrawingML per-mil (50000 ≈ 50%). Used by
   * `bentConnector3` to position the bend; defaults to 50000 when
   * the preset wants an adjust value and none is authored.
   */
  adj1?: number;
};
