// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeBullet } from "./ShapeBullet.js";
import type { TextRun } from "./TextRun.js";

export type ShapeParagraph = {
  align?: string;
  marLEmu?: number;
  indentEmu?: number;
  level?: number;
  lineSpacingPct?: number;
  lineSpacingPts?: number;
  spaceBeforePct?: number;
  spaceBeforePts?: number;
  spaceAfterPct?: number;
  spaceAfterPts?: number;
  bullet?: ShapeBullet;
  runs: Array<TextRun>;
};
