// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRun } from "./TextRun.js";

/**
 * One `<a:p>` paragraph inside a shape's text body.
 */
export type ShapeParagraph = {
  /**
   * `<a:pPr algn="..."/>` — `l`/`ctr`/`r`/`just`. None ⇒ `l`.
   */
  align?: string;
  /**
   * Plain-text runs. We reuse the SST `TextRun` shape since the
   * rendered properties overlap (text, bold/italic, size, color,
   * font name).
   */
  runs: Array<TextRun>;
};
