// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeNode } from "./ShapeNode.js";

export type Shape = { nodes: Array<ShapeNode> };
