// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";

export type ShapeBullet = {
  kind: string;
  char?: string;
  autoNumType?: string;
  autoNumStartAt?: number;
  font?: string;
  color?: Color;
  sizePct?: number;
  sizePts?: number;
};
