// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeParagraph } from "./ShapeParagraph.js";

/**
 * One leaf `<xdr:sp>` (or `<xdr:cxnSp>`) positioned inside the drawing
 * anchor's bbox via fractional coordinates (0..1). The renderer maps
 * these to the anchor's resolved pixel rect.
 */
export type ShapeNode = {
  /**
   * Fractional bbox inside the drawing-anchor's resolved pixel rect.
   */
  relX: number;
  relY: number;
  relW: number;
  relH: number;
  /**
   * `<a:prstGeom prst="..."/>` token (`rect`, `roundRect`, `ellipse`,
   * `leftArrow`, …). None ⇒ no preset (custom geometry); renderer
   * falls back to a plain rectangle.
   */
  preset?: string;
  /**
   * Resolved `#RRGGBB` fill color from `<a:solidFill>`. `None` when
   * `<a:noFill/>` is authored or no fill is present.
   */
  fill?: string;
  /**
   * Resolved `#RRGGBB` outline color. `None` when `<a:noFill/>` or
   * `<a:ln>` is absent.
   */
  outlineColor?: string;
  /**
   * Outline stroke width in EMU. `None` ⇒ Excel default (~9525 EMU
   * = 1pt). 0 ⇒ hairline.
   */
  outlineWidthEmu?: number;
  /**
   * `<a:bodyPr anchor="..."/>` vertical anchor (`t`/`ctr`/`b`).
   * Default `t` (top).
   */
  textAnchor?: string;
  /**
   * Rotation in 1/60000 degree units (OOXML's `rot` attr unit).
   * `None` ⇒ 0.
   */
  rotation?: number;
  /**
   * Text paragraphs.
   */
  paragraphs: Array<ShapeParagraph>;
  /**
   * `<a:bodyPr wrap="..."/>` token (`square` ⇒ wrap on word
   * boundaries; `none` ⇒ no wrap). Default `square` (Excel's
   * implicit default when the attr is absent).
   */
  textWrap?: string;
  /**
   * Inline picture node — when this is `Some(...)`, the node
   * renders an embedded raster image (`<xdr:pic>` nested inside
   * `<xdr:grpSp>`) instead of a `prstGeom` rect. The string is a
   * `data:<mime>;base64,...` URI (same encoding the top-level
   * `Image.dataUri` uses, sharing the renderer image cache).
   * Fill / outline / paragraphs are ignored when this is set.
   */
  imageDataUri?: string;
  /**
   * `<a:srcRect l="" t="" r="" b=""/>` crop, in 1/1000 percent of
   * the source image dimensions. Length-4 vec: [left, top, right,
   * bottom]. Renderer uses these as fractional crop insets when
   * painting `image_data_uri`.
   */
  imageSrcRect?: Array<number>;
};
