// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Sparkline = { r: number; c: number; formula?: string; values: Array<number | null> };
