// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Border } from "./Border.js";
import type { CellFormat } from "./CellFormat.js";
import type { Fill } from "./Fill.js";
import type { Font } from "./Font.js";
import type { NumberFormat } from "./NumberFormat.js";

export type Styles = {
  fonts: Array<Font>;
  fills: Array<Fill>;
  borders: Array<Border>;
  cellXfs: Array<CellFormat>;
  numFmts: Array<NumberFormat>;
  defaultFont: string;
  defaultFontSize: number;
};
