// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `<tableStyleInfo>` — picks one of Excel's built-in table styles
 * (e.g. `TableStyleMedium2`) and toggles the four banding axes.
 * Custom user table styles (`<tableStyles>` in styles.xml) ARE
 * resolved — they're surfaced on `WorkbookLayout.table_styles` and
 * the renderer looks them up by `name`. When neither a built-in nor
 * a custom match is found the renderer falls back to the default
 * Medium2 accent.
 */
export type TableStyle = {
  /**
   * Built-in style name, e.g. `TableStyleMedium2`. The trailing
   * integer indexes into the workbook's accent colors
   * (`(N-1) % 6 → accent{1..6}`).
   */
  name: string;
  showFirstColumn: boolean;
  showLastColumn: boolean;
  showRowStripes: boolean;
  showColumnStripes: boolean;
};
