// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Merge } from "./Merge.js";
import type { TableColumn } from "./TableColumn.js";
import type { TableStyle } from "./TableStyle.js";

export type Table = {
  name: string;
  displayName: string;
  range: Merge;
  headerRowCount: number;
  totalsRowCount: number;
  columns: Array<TableColumn>;
  style?: TableStyle;
  hasAutoFilter: boolean;
};
