// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableFilterArrow = {
  r: number;
  c: number;
  columnOffset: number;
  columnName: string;
  rangeRef: string;
};
