// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomTableStyle } from "./CustomTableStyle.js";
import type { Dxf } from "./Dxf.js";
import type { Sheet } from "./Sheet.js";
import type { Styles } from "./Styles.js";
import type { TextRun } from "./TextRun.js";
import type { Theme } from "./Theme.js";

export type WorkbookLayout = {
  sheets: Array<Sheet>;
  styles: Styles;
  sharedStrings: Array<string>;
  /**
   * Rich-text runs aligned with `shared_strings` by index. Inner `Vec`
   * is empty when the SST entry is plain text (no `<r>` runs); the
   * renderer falls back to the cell's base font in that case.
   */
  sharedStringRuns: Array<Array<TextRun>>;
  /**
   * Differential formats (`<dxfs>`) — overlay style records that
   * conditional-formatting rules and table styles reference by index.
   * Indexed by `CfRule.dxf_id`.
   */
  dxfs: Array<Dxf>;
  /**
   * Custom user-defined table styles (`<tableStyles><tableStyle>`).
   * Excel's *built-in* styles (`TableStyleMedium2`, `TableStyleLight1`,
   * …) are not enumerated here — the renderer derives those from
   * the trailing integer in the style name. Custom styles need the
   * per-element `dxfId` references because the fill/font live in
   * the workbook's `dxfs` table, not the style name. Look up by
   * `TableStyle.name` from `Table.style`.
   */
  tableStyles: Array<CustomTableStyle>;
  /**
   * Workbook theme (`xl/theme/theme1.xml`) — color palette + font scheme.
   * `Color { theme: N }` references resolve against `theme.colors[N]`.
   * `None` when the workbook ships no theme part (rare); renderer falls
   * back to the Office 2007+ default palette.
   */
  theme?: Theme;
  /**
   * Index into `sheets` of the tab that should be focused on initial
   * render. Mirrors `xl/workbook.xml`'s `<workbookView activeTab="N"/>`.
   * `None` (or omitted) → renderer defaults to sheet 0.
   */
  activeSheetIndex?: number;
};
