import type { Sheet as WireSheet } from "./schema/Sheet.js";
import type { DecodedCells, DecodedRowMeta } from "./columnar.js";
export interface Sheet extends WireSheet {
  decodedCells: DecodedCells;
  decodedRowMeta: DecodedRowMeta;
}

export type {
  Border,
  BorderLine,
  Cell,
  CellFormat,
  CellRef,
  CfColorScale,
  CfColorScaleStop,
  CfDataBar,
  CfIconSet,
  CfRule,
  CfvoStop,
  Chart,
  ChartSeries,
  DataLabels,
  PointDataLabel,
  Col,
  Color,
  Comment,
  ConditionalFormat,
  CustomTableStyle,
  Drawing,
  DrawingAnchor,
  Dxf,
  Fill,
  Font,
  GradientStop,
  Freeze,
  Hyperlink,
  Image,
  LineEnd,
  Merge,
  NumberFormat,
  OutlinePr,
  Pivot,
  Shape,
  ShapeGradient,
  ShapeGradientStop,
  ShapeNode,
  ShapeOuterShadow,
  ShapeParagraph,
  Sparkline,
  SparklineGroup,
  Styles,
  Table,
  TableColumn,
  TableStyle,
  TextRun,
  Theme,
  WorkbookLayout,
} from "./schema/index.js";
