// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderLine } from "./BorderLine.js";

export type Border = { left?: BorderLine, right?: BorderLine, top?: BorderLine, bottom?: BorderLine, 
/**
 * `<border diagonalUp="1">`: paint the `/` slash
 * (bottom-left → top-right).
 */
diagonalUp: boolean, 
/**
 * `<border diagonalDown="1">`: paint the `\` slash
 * (top-left → bottom-right).
 */
diagonalDown: boolean, 
/**
 * Style + color for whichever diagonal(s) `diagonalUp`/`diagonalDown`
 * enabled. Both diagonals share one `<diagonal>` child in OOXML.
 */
diagonal?: BorderLine, };
