// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";

export type BorderLine = { 
/**
 * "thin","medium","thick","double","dotted","dashed","hair", etc.
 */
style: string, color?: Color, };
