// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellFormat = {
  fontId?: number;
  fillId?: number;
  borderId?: number;
  numFmtId?: number;
  /**
   * "left","center","right","general","fill","justify" (lower-case).
   */
  horizontalAlignment?: string;
  /**
   * "top","center","bottom".
   */
  verticalAlignment?: string;
  wrapText: boolean;
  indent?: number;
  textRotation?: number;
};
