// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfvoStop } from "./CfvoStop.js";

/**
 * `iconSet` conditional-format rule. Picks one icon from a named
 * preset (e.g. `3TrafficLights1`, `5Arrows`) per cell based on the
 * value's position in the user-supplied thresholds. Mirrors
 * `<x:iconSet>` in worksheet XML; ECMA-376 §18.3.1.49.
 *
 * `cfvos.len()` always equals N (3/4/5) and the first stop is the
 * implicit "low" icon — the matching index for a value v is the
 * largest k such that v meets the threshold at cfvos[k]. Per spec
 * the comparison is `>=` by default and `>` when `gte=false` on the
 * stop, but legacy `<x:iconSet>` doesn't expose `gte` so we treat
 * every threshold as `>=`.
 */
export type CfIconSet = { 
/**
 * One of the OOXML preset IDs: `3Arrows`, `3ArrowsGray`,
 * `3Flags`, `3TrafficLights1`, `3TrafficLights2`, `3Signs`,
 * `3Symbols`, `3Symbols2`, `4Arrows`, `4ArrowsGray`,
 * `4RedToBlack`, `4Rating`, `4TrafficLights`, `5Arrows`,
 * `5ArrowsGray`, `5Rating`, `5Quarters`.
 */
iconSet: string, 
/**
 * N stops (3, 4, or 5). `cfvos[0]` is the low-icon anchor
 * (typically `percent 0`); subsequent stops define the
 * thresholds for the higher icons.
 */
cfvos: Array<CfvoStop>, 
/**
 * When false, the cell value is hidden and only the icon paints.
 */
showValue: boolean, 
/**
 * When true, the icon order is reversed (high values get the
 * first icon in the set).
 */
reverse: boolean, };
