// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Col = { min: number, max: number, widthPx: number, styleIndex?: number, hidden: boolean, 
/**
 * OOXML `<col outlineLevel="N">` (0..=7). 0 = no grouping; the
 * renderer paints a bracket above the column header(s) covering
 * each contiguous run at level >= 1. Spec caps at 7.
 */
outlineLevel: number, };
