// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";

export type Fill = { 
/**
 * "solid", "none", "pattern", "gradient".
 */
patternType?: string, fgColor?: Color, bgColor?: Color, 
/**
 * Gradient stop colors in source order. v0 renderer uses the first and
 * last stop for a linear left→right fill.
 */
gradientStops: Array<Color>, };
