// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { GradientStop } from "./GradientStop.js";

export type Fill = { 
/**
 * "solid", "none", "pattern", "gradient".
 */
patternType?: string, fgColor?: Color, bgColor?: Color, 
/**
 * Gradient stops in source order. Each stop carries its OOXML
 * `position` (0..1 along the gradient axis for `linear`, or 0..1
 * from the inner convergence rect outward for `path`/radial).
 */
gradientStops: Array<GradientStop>, 
/**
 * `"linear"` (default) or `"path"` (radial-ish, with a rectangular
 * inner-convergence region). Only meaningful when
 * `pattern_type == "gradient"`.
 */
gradientType?: string, 
/**
 * Linear gradient angle in degrees (OOXML `degree`). 0 = left→right,
 * 90 = top→bottom, 180 = right→left, 270 = bottom→top. Ignored when
 * `gradient_type == "path"`.
 */
gradientDegree?: number, 
/**
 * Path-gradient inner-convergence rectangle, expressed as fractions
 * of cell width/height inset from each side (0..1). Defaults to 0
 * when missing (rect collapses to a point at the relevant corner).
 * Ignored unless `gradient_type == "path"`.
 */
gradientLeft?: number, gradientRight?: number, gradientTop?: number, gradientBottom?: number, };
