// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";

export type Font = { name?: string, size?: number, bold: boolean, italic: boolean, underline: boolean, 
/**
 * OOXML `<u val="..."/>` variant when not the default `single`.
 * See `TextRun.underline_style` for values + renderer behavior.
 */
underlineStyle?: string, strike: boolean, color?: Color, };
