// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `<outlinePr>` defaults from `<sheetPr>`. Both fields default to true
 * when `<outlinePr>` is absent (matches Excel/OOXML spec).
 */
export type OutlinePr = { summaryBelow: boolean, summaryRight: boolean, };
