// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellRef } from "./CellRef.js";
import type { Merge } from "./Merge.js";

/**
 * One `<pivotTableDefinition>` — just enough to paint the cosmetic
 * chrome. The actual values are already in `Sheet.rows` (Excel/SpreadJS
 * always materialize pivot output cells into the sheet's `<sheetData>`
 * with explicit cell xfs).
 */
export type Pivot = { 
/**
 * Internal name (`name=` attr on `<pivotTableDefinition>`).
 */
name: string, 
/**
 * Bounding range covered by the pivot, including header strip
 * and grand-total row/column. Mirrors `<location ref=".">`.
 */
range: Merge, 
/**
 * Cells (1-based r,c) that should get a filter-dropdown chevron.
 * Computed by the extractor from the pivot's `<location>` +
 * `<rowFields>` / `<colFields>` so the renderer doesn't need to
 * re-derive them. Empty for pivots with no axis fields.
 */
filterArrowCells: Array<CellRef>, };
