// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RowMetaBlob = { count: number, 
/**
 * 1-based row indices, u32 LE. Sorted ascending.
 */
index: string, 
/**
 * f32 LE; NaN means "use sheet's default row height".
 */
heightPx: string, 
/**
 * i32 LE; -1 = no row-level style override.
 */
styleIdx: string, 
/**
 * u8: 0/1.
 */
hidden: string, 
/**
 * u8: OOXML `<row outlineLevel="N">`, 0..=7. 0 = no grouping.
 * Empty string when every row is at level 0 (the common case);
 * renderer treats absent blob as all-zeros.
 */
outlineLevel: string, };
