// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Col } from "./Col.js";
import type { Comment } from "./Comment.js";
import type { ConditionalFormat } from "./ConditionalFormat.js";
import type { Drawing } from "./Drawing.js";
import type { Freeze } from "./Freeze.js";
import type { Hyperlink } from "./Hyperlink.js";
import type { Merge } from "./Merge.js";
import type { Pivot } from "./Pivot.js";
import type { Row } from "./Row.js";
import type { Table } from "./Table.js";

export type Sheet = { index: number, name: string, 
/**
 * 1-based, inclusive. (0,0) when sheet is empty.
 */
maxRow: number, maxCol: number, 
/**
 * Default column width in px.
 */
defaultColWidthPx: number, 
/**
 * Default row height in px.
 */
defaultRowHeightPx: number, 
/**
 * Custom column widths (sparse). Each entry covers cols `min..=max`.
 */
cols: Array<Col>, rows: Array<Row>, merges: Array<Merge>, freeze?: Freeze, showGridLines: boolean, 
/**
 * Conditional formatting blocks, in source order. Renderer applies
 * highest-`priority` rule per cell.
 */
conditionalFormats: Array<ConditionalFormat>, 
/**
 * Drawings (charts, images) anchored on this sheet.
 */
drawings: Array<Drawing>, 
/**
 * `<table>` ListObjects on this sheet (one entry per
 * `xl/tables/tableN.xml` part referenced by the worksheet).
 * Renderer paints the table's visual chrome (header band, banded
 * rows, filter-arrow glyphs); no filtering interactivity.
 */
tables: Array<Table>, 
/**
 * `<hyperlink>` entries from the worksheet's `<hyperlinks>` block.
 * External `r:id` rels are resolved to absolute URLs at extract
 * time; `location` carries internal in-workbook jumps (e.g.
 * `'Sheet 2'!A1`). Renderer paints blue+underline over the cells
 * in `range` and (in the browser) wires a click handler.
 */
hyperlinks: Array<Hyperlink>, 
/**
 * Cell comments from the worksheet's comments part. Renderer
 * paints a small red triangle in the top-right of `r,c` and
 * (in the browser) shows the body in a hover popover.
 */
comments: Array<Comment>, 
/**
 * Pivot tables anchored on this sheet (one entry per
 * `xl/pivotTables/pivotTableN.xml` referenced by the worksheet).
 * We treat pivots as cosmetic chrome only — the materialized
 * result cells already live in `Sheet.rows` with explicit
 * styling, so the renderer just paints filter-arrow chevrons on
 * the row/column field-header cells. No filtering / refresh /
 * expand-collapse interactivity. ("Cheap path" in PARITY.md.)
 */
pivots: Array<Pivot>, };
