// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `<x14:sparkline>` — anchored at one cell, drawing values from
 * `formula`. Values are resolved post-extract (see
 * `lib.rs::resolve_sparkline_refs`); preserve `None` for empty/text
 * cells so the renderer can honor `displayEmptyCellsAs`.
 */
export type Sparkline = {
  /**
   * 1-based anchor cell row.
   */
  r: number;
  /**
   * 1-based anchor cell column.
   */
  c: number;
  /**
   * Source-data formula, e.g. `"Sheet1!B2:G2"`. Kept for debugging.
   */
  formula?: string;
  /**
   * Resolved data values in source order. `None` entries indicate
   * empty / non-numeric source cells; the renderer interprets them
   * according to the group's `displayEmptyCellsAs`.
   */
  values: Array<number | null>;
};
