// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableColumn = { name: string, 
/**
 * `sum`, `average`, `count`, `countNums`, `min`, `max`, `stdDev`,
 * `var`, `custom`. None ⇒ no totals function for this column.
 */
totalsRowFunction?: string, 
/**
 * Literal label shown in the totals row (e.g. "Total").
 */
totalsRowLabel?: string, };
