// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Merge } from "./Merge.js";
import type { TableColumn } from "./TableColumn.js";
import type { TableStyle } from "./TableStyle.js";

/**
 * One `<table>` ListObject — a named range with banded styling, an
 * optional header row, and an optional totals row. Mirrors
 * `xl/tables/tableN.xml` (CT_Table). The renderer treats this as
 * pure cosmetic chrome; the cell values themselves stay in `Sheet.rows`.
 */
export type Table = { 
/**
 * Internal name (`name` attr; falls back to `displayName`).
 */
name: string, 
/**
 * User-visible name shown in the formula bar's name box.
 */
displayName: string, 
/**
 * Inclusive range covered by the table, including header + totals.
 */
range: Merge, 
/**
 * 0 or 1. Excel's default is 1; some `headerRowCount="0"` tables
 * (used as ranges-with-style) skip the header band.
 */
headerRowCount: number, 
/**
 * 0 or 1.
 */
totalsRowCount: number, 
/**
 * Per-column metadata (header label, totals-row label/function).
 * `columns.len()` always equals `range.c2 - range.c1 + 1`.
 */
columns: Array<TableColumn>, style?: TableStyle, 
/**
 * True when the table has an `<autoFilter>` child — drives whether
 * the renderer paints filter-arrow glyphs in the header cells.
 */
hasAutoFilter: boolean, };
