// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";

/**
 * One styled span inside a rich-text cell. Mirrors `<r><rPr/><t/></r>` in
 * OOXML. Properties left as `None`/`false` mean "inherit from the cell's
 * own font".
 */
export type TextRun = { text: string, bold: boolean, italic: boolean, underline: boolean, 
/**
 * OOXML `<u val="..."/>` variant when not the default `single`.
 * One of `"single"` / `"double"` / `"singleAccounting"` /
 * `"doubleAccounting"`. Absent = `single` (matches the OOXML default).
 * Renderer paints `double*` as two parallel strokes; the
 * accounting variants currently fall through to single/double
 * (the "line extends across the full cell width" semantics are
 * not honored yet — tracked in PARITY.md).
 */
underlineStyle?: string, strike: boolean, 
/**
 * Font size in points (matches `Font.size`).
 */
size?: number, fontName?: string, color?: Color, };
