// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";

/**
 * One styled span inside a rich-text cell. Mirrors `<r><rPr/><t/></r>` in
 * OOXML. Properties left as `None`/`false` mean "inherit from the cell's
 * own font".
 */
export type TextRun = { text: string, bold: boolean, italic: boolean, underline: boolean, strike: boolean, 
/**
 * Font size in points (matches `Font.size`).
 */
size?: number, fontName?: string, color?: Color, };
