// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workbook theme: a 12-entry color palette plus font scheme names.
 *
 * `colors` is pre-remapped to the spreadsheet `theme="N"` indexing
 * convention (the OOXML quirk where lt1/dk1 and lt2/dk2 are swapped
 * relative to the XML element order in `<a:clrScheme>`):
 *
 * | idx | role     | xml element |
 * |-----|----------|-------------|
 * | 0   | lt1      | `<a:lt1>`   |
 * | 1   | dk1      | `<a:dk1>`   |
 * | 2   | lt2      | `<a:lt2>`   |
 * | 3   | dk2      | `<a:dk2>`   |
 * | 4-9 | accent1-6| `<a:accent1>`..`<a:accent6>` |
 * | 10  | hlink    | `<a:hlink>` |
 * | 11  | folHlink | `<a:folHlink>` |
 *
 * Each entry is a 6-char hex string `"RRGGBB"` (no leading `#`,
 * matching the rest of `Color.rgb`). When the source theme uses an
 * `<a:sysClr>` with a `lastClr` fallback we resolve to that; if a
 * color can't be resolved (preset names, scrgb percentages we don't
 * handle yet) we fall back to the Office default for that slot.
 */
export type Theme = {
  /**
   * 12 hex colors, indexed by `Color.theme`.
   */
  colors: Array<string>;
  /**
   * `<a:majorFont>` Latin typeface (e.g. "Calibri Light"). Used for
   * chart titles when the chart references the major theme font.
   */
  majorFont?: string;
  /**
   * `<a:minorFont>` Latin typeface (e.g. "Calibri"). The default body
   * font; cells with no explicit `<rFont>` inherit this.
   */
  minorFont?: string;
};
